/*
 * Copyright (c) 2026 the Eclipse Milo Authors
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 */

package org.eclipse.milo.opcua.stack.core.security;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.security.KeyPair;
import java.security.cert.X509Certificate;
import java.util.List;
import org.bouncycastle.asn1.x500.X500Name;
import org.bouncycastle.jce.provider.BouncyCastleProvider;
import org.bouncycastle.operator.jcajce.JcaContentVerifierProviderBuilder;
import org.bouncycastle.pkcs.PKCS10CertificationRequest;
import org.eclipse.milo.opcua.stack.core.NodeIds;
import org.eclipse.milo.opcua.stack.core.StatusCodes;
import org.eclipse.milo.opcua.stack.core.UaException;
import org.eclipse.milo.opcua.stack.core.types.builtin.ByteString;
import org.junit.jupiter.api.Test;

class AbstractCertificateFactoryTest {

  @SuppressWarnings("deprecation")
  @Test
  void rsaSha256CompatibilityFactoryRejectsEccCertificateTypes() throws Exception {
    RsaSha256CertificateFactory factory =
        new RsaSha256CertificateFactory() {
          @Override
          protected X509Certificate[] createRsaSha256CertificateChain(KeyPair keyPair) {
            return new X509Certificate[0];
          }
        };
    KeyPair keyPair = factory.createRsaSha256KeyPair();

    assertThrows(
        UnsupportedOperationException.class,
        () -> factory.createKeyPair(NodeIds.EccNistP256ApplicationCertificateType));
    assertThrows(
        UnsupportedOperationException.class,
        () ->
            factory.createCertificateChain(NodeIds.EccNistP256ApplicationCertificateType, keyPair));
    assertThrows(
        UnsupportedOperationException.class,
        () ->
            factory.createSigningRequest(
                NodeIds.EccNistP256ApplicationCertificateType,
                keyPair,
                new X500Name("CN=ecc"),
                "urn:eclipse:milo:test",
                List.of(),
                List.of()));
  }

  // A factory can recognize an ECC CertificateType without being able to issue a certificate chain
  // for it. GDS-style callers should be able to preserve that as Bad_NotSupported.
  @Test
  void defaultEccCertificateChainHooksReportNotSupported() throws Exception {
    AbstractCertificateFactory factory =
        new AbstractCertificateFactory() {
          @Override
          protected X509Certificate[] createRsaSha256CertificateChain(KeyPair keyPair) {
            return new X509Certificate[0];
          }
        };
    KeyPair keyPair = factory.createEccNistP256KeyPair();

    UaException exception =
        assertThrows(
            UaException.class,
            () ->
                factory.createCertificateChain(
                    NodeIds.EccNistP256ApplicationCertificateType, keyPair));

    assertEquals(StatusCodes.Bad_NotSupported, exception.getStatusCode().value());
  }

  // Brainpool P-256 keys are generated by BC, so CSR signing and verification must stay on a
  // provider that understands the Brainpool curve.
  @Test
  void brainpoolP256SigningRequestUsesBouncyCastleProvider() throws Exception {
    TestCertificateFactory factory = new TestCertificateFactory();
    KeyPair keyPair = factory.createEccBrainpoolP256r1KeyPair();

    ByteString csrBytes =
        factory.createSigningRequest(
            NodeIds.EccBrainpoolP256r1ApplicationCertificateType,
            keyPair,
            new X500Name("CN=brainpool-p256"),
            "urn:eclipse:milo:test",
            List.of("localhost"),
            List.of("127.0.0.1"));
    PKCS10CertificationRequest csr = new PKCS10CertificationRequest(csrBytes.bytesOrEmpty());

    assertTrue(
        csr.isSignatureValid(
            new JcaContentVerifierProviderBuilder()
                .setProvider(new BouncyCastleProvider())
                .build(csr.getSubjectPublicKeyInfo())));
  }

  // Brainpool P-384 keys are generated by BC, so CSR signing and verification must stay on a
  // provider that understands the Brainpool curve.
  @Test
  void brainpoolP384SigningRequestUsesBouncyCastleProvider() throws Exception {
    TestCertificateFactory factory = new TestCertificateFactory();
    KeyPair keyPair = factory.createEccBrainpoolP384r1KeyPair();

    ByteString csrBytes =
        factory.createSigningRequest(
            NodeIds.EccBrainpoolP384r1ApplicationCertificateType,
            keyPair,
            new X500Name("CN=brainpool-p384"),
            "urn:eclipse:milo:test",
            List.of("localhost"),
            List.of("127.0.0.1"));
    PKCS10CertificationRequest csr = new PKCS10CertificationRequest(csrBytes.bytesOrEmpty());

    assertTrue(
        csr.isSignatureValid(
            new JcaContentVerifierProviderBuilder()
                .setProvider(new BouncyCastleProvider())
                .build(csr.getSubjectPublicKeyInfo())));
  }

  // Curve448 CSRs use Ed448 signatures. X448 is the ephemeral key-agreement curve, not an
  // application authentication key.
  @Test
  void curve448SigningRequestUsesEd448() throws Exception {
    TestCertificateFactory factory = new TestCertificateFactory();
    KeyPair keyPair = factory.createEccCurve448KeyPair();

    ByteString csrBytes =
        factory.createSigningRequest(
            NodeIds.EccCurve448ApplicationCertificateType,
            keyPair,
            new X500Name("CN=curve448"),
            "urn:eclipse:milo:test",
            List.of("localhost"),
            List.of("127.0.0.1"));
    PKCS10CertificationRequest csr = new PKCS10CertificationRequest(csrBytes.bytesOrEmpty());

    assertTrue(
        csr.isSignatureValid(
            new JcaContentVerifierProviderBuilder()
                .setProvider(new BouncyCastleProvider())
                .build(csr.getSubjectPublicKeyInfo())));
  }
}
