/*
 * Copyright (c) 2026 the Eclipse Milo Authors
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 */

package org.eclipse.milo.opcua.sdk.server.conditions;

import static java.util.Objects.requireNonNull;
import static org.eclipse.milo.opcua.stack.core.types.builtin.unsigned.Unsigned.ubyte;
import static org.eclipse.milo.opcua.stack.core.types.builtin.unsigned.Unsigned.uint;
import static org.eclipse.milo.opcua.stack.core.types.builtin.unsigned.Unsigned.ushort;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.util.List;
import org.eclipse.milo.opcua.sdk.client.subscriptions.OpcUaSubscription;
import org.eclipse.milo.opcua.sdk.core.Reference;
import org.eclipse.milo.opcua.sdk.server.model.objects.AlarmConditionTypeNode;
import org.eclipse.milo.opcua.sdk.server.nodes.UaObjectNode;
import org.eclipse.milo.opcua.sdk.test.AbstractClientServerTest;
import org.eclipse.milo.opcua.sdk.test.EventTestSupport;
import org.eclipse.milo.opcua.sdk.test.TestNamespace;
import org.eclipse.milo.opcua.stack.core.NodeIds;
import org.eclipse.milo.opcua.stack.core.UaException;
import org.eclipse.milo.opcua.stack.core.types.builtin.ByteString;
import org.eclipse.milo.opcua.stack.core.types.builtin.LocalizedText;
import org.eclipse.milo.opcua.stack.core.types.builtin.NodeId;
import org.eclipse.milo.opcua.stack.core.types.builtin.Variant;
import org.eclipse.milo.opcua.stack.core.types.structured.CallMethodRequest;
import org.eclipse.milo.opcua.stack.core.types.structured.CallMethodResult;
import org.eclipse.milo.opcua.stack.core.types.structured.CallResponse;
import org.eclipse.milo.opcua.stack.core.types.structured.EventFilter;
import org.jspecify.annotations.Nullable;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

/**
 * Client-visible tests for the WP4 alarm lifecycle: {@code setActive}-driven activation and
 * deactivation with the alarm Retain formula, EventId minting across activations, and the honest
 * address-space contract for optional alarm members v1 does not support.
 */
public class AlarmConditionTest extends AbstractClientServerTest {

  /** Severity of all events generated by the test alarm; the where clause matches on it. */
  private static final int TEST_SEVERITY = 556;

  private AlarmCondition alarm;
  private NodeId conditionId;
  private NodeId inputNodeId;

  @Override
  protected void configureTestNamespace(TestNamespace namespace) {
    namespace.configure(
        (context, nodeManager) -> {
          var source =
              new UaObjectNode(
                  context,
                  newNodeId("AlarmConditionTest/Source"),
                  newQualifiedName("AlarmConditionTest/Source"),
                  LocalizedText.english("AlarmConditionTest/Source"),
                  LocalizedText.NULL_VALUE,
                  uint(0),
                  uint(0),
                  ubyte(0));

          source.addReference(
              new Reference(
                  source.getNodeId(),
                  NodeIds.HasTypeDefinition,
                  NodeIds.BaseObjectType.expanded(),
                  true));

          source.addReference(
              new Reference(
                  source.getNodeId(),
                  NodeIds.HasComponent,
                  NodeIds.ObjectsFolder.expanded(),
                  Reference.Direction.INVERSE));

          nodeManager.addNode(source);

          inputNodeId = newNodeId("AlarmConditionTest/Input");

          try {
            alarm =
                AlarmCondition.create(
                    context,
                    b ->
                        b.nodeId(newNodeId("AlarmConditionTest/Alarm"))
                            .browseName(newQualifiedName("TestAlarm"))
                            .conditionSource(source)
                            .inputNode(inputNodeId)
                            .severity(ushort(TEST_SEVERITY)));
          } catch (UaException e) {
            throw new RuntimeException(e);
          }

          server.getConditionManager().register(alarm);
          conditionId = alarm.getConditionId();
        });
  }

  @BeforeEach
  void resetAlarmState() {
    alarm.setInterceptor(new ConditionMethodInterceptor() {});
    alarm.setActive(false);
    alarm.setAcked(true);
  }

  @Test
  void fullLifecycleActivateAcknowledgeDeactivateReactivate() throws Exception {
    var subscription = new OpcUaSubscription(client);
    subscription.create();

    try {
      List<Variant[]> events = monitorEvents(subscription);

      // Activation: one event, ActiveState/Id=true, needing acknowledgement, Retain=true.
      alarm.setActive(true);
      EventTestSupport.awaitEvent(
          events,
          "activation event",
          e -> "Active".equals(messageOf(e)) && activeIdOf(e) && !ackedIdOf(e) && retainOf(e));
      assertTrue(alarm.isActive());
      assertTrue(alarm.isRetained());

      // Acknowledge with the activation EventId; the alarm stays retained while active.
      ByteString eventId = alarm.currentBranch().getLastEventId();
      CallMethodResult ack = acknowledge(eventId);
      assertTrue(requireNonNull(ack.getStatusCode()).isGood());
      EventTestSupport.awaitEvent(
          events,
          "acknowledged while active",
          e -> "Acknowledged".equals(messageOf(e)) && ackedIdOf(e) && retainOf(e));
      assertTrue(alarm.isRetained());

      // Deactivation: inactive and acknowledged, so the Retain retraction fires per formula.
      alarm.setActive(false);
      EventTestSupport.awaitEvent(
          events,
          "deactivation retraction",
          e -> "Inactive".equals(messageOf(e)) && !activeIdOf(e) && !retainOf(e));
      assertFalse(alarm.isRetained());

      // Re-activation mints a fresh EventId that Acknowledge accepts.
      alarm.setActive(true);
      EventTestSupport.awaitEvent(
          events,
          "re-activation event",
          e -> "Active".equals(messageOf(e)) && !ackedIdOf(e) && retainOf(e));

      ByteString freshEventId = alarm.currentBranch().getLastEventId();
      assertNotEquals(eventId, freshEventId);

      CallMethodResult reAck = acknowledge(freshEventId);
      assertTrue(requireNonNull(reAck.getStatusCode()).isGood());
      assertTrue(alarm.isAcked());
    } finally {
      subscription.delete();
    }
  }

  @Test
  void unsupportedOptionalMembersAreNotExposed() {
    AlarmConditionTypeNode node = alarm.getNode();

    // Built without withShelving: no ShelvingState component or shelving surface.
    assertNull(node.getShelvingStateNode());
    assertNull(alarm.getShelvingState());

    // Optional method nodes without backing state in v1 are deleted, not left dangling.
    assertNull(node.getSilenceMethodNode());
    assertNull(node.getSuppressMethodNode());
    assertNull(node.getSuppress2MethodNode());
    assertNull(node.getUnsuppressMethodNode());
    assertNull(node.getRemoveFromServiceMethodNode());
    assertNull(node.getPlaceInServiceMethodNode());
    assertNull(node.getResetMethodNode());
    assertNull(node.getGetGroupMembershipsMethodNode());

    // Acknowledge-auto-silences (§5.8.2) is a no-op in v1: there is no SilenceState.
    assertNull(node.getSilenceStateNode());

    // InputNode is wired from the builder; SuppressedOrShelved starts false.
    assertEquals(inputNodeId, node.getInputNode());
    assertEquals(Boolean.FALSE, node.getSuppressedOrShelved());
  }

  private CallMethodResult acknowledge(ByteString eventId) throws Exception {
    return call(
        conditionId,
        NodeIds.AcknowledgeableConditionType_Acknowledge,
        new Variant(eventId),
        new Variant(LocalizedText.NULL_VALUE));
  }

  private CallMethodResult call(NodeId objectId, NodeId methodId, Variant... inputs)
      throws Exception {

    CallResponse response = client.call(List.of(new CallMethodRequest(objectId, methodId, inputs)));

    return requireNonNull(response.getResults())[0];
  }

  /**
   * Monitor events on the Server Object, selecting [Message, Severity, AckedState/Id,
   * ActiveState/Id, Retain] and matching only events with Severity == {@link #TEST_SEVERITY}.
   */
  private List<Variant[]> monitorEvents(OpcUaSubscription subscription) throws Exception {
    EventFilter eventFilter =
        EventTestSupport.severityEventFilter(
            TEST_SEVERITY,
            EventTestSupport.eventField(NodeIds.BaseEventType, "Message"),
            EventTestSupport.eventField(NodeIds.BaseEventType, "Severity"),
            EventTestSupport.eventField(NodeIds.AcknowledgeableConditionType, "AckedState", "Id"),
            EventTestSupport.eventField(NodeIds.AlarmConditionType, "ActiveState", "Id"),
            EventTestSupport.eventField(NodeIds.ConditionType, "Retain"));

    return EventTestSupport.monitorEvents(subscription, NodeIds.Server, eventFilter);
  }

  private static @Nullable String messageOf(Variant[] eventFields) {
    return eventFields[0].value() instanceof LocalizedText text ? text.text() : null;
  }

  private static boolean ackedIdOf(Variant[] eventFields) {
    return Boolean.TRUE.equals(eventFields[2].value());
  }

  private static boolean activeIdOf(Variant[] eventFields) {
    return Boolean.TRUE.equals(eventFields[3].value());
  }

  private static boolean retainOf(Variant[] eventFields) {
    return Boolean.TRUE.equals(eventFields[4].value());
  }
}
