/*
 * Copyright (c) 2026 the Eclipse Milo Authors
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 */

package org.eclipse.milo.opcua.sdk.server.conditions;

import static java.util.Objects.requireNonNull;
import static org.eclipse.milo.opcua.stack.core.types.builtin.unsigned.Unsigned.ubyte;
import static org.eclipse.milo.opcua.stack.core.types.builtin.unsigned.Unsigned.uint;
import static org.eclipse.milo.opcua.stack.core.types.builtin.unsigned.Unsigned.ushort;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.fail;

import java.util.List;
import java.util.function.Predicate;
import org.eclipse.milo.opcua.sdk.client.OpcUaClientConfigBuilder;
import org.eclipse.milo.opcua.sdk.client.identity.UsernameProvider;
import org.eclipse.milo.opcua.sdk.client.subscriptions.OpcUaSubscription;
import org.eclipse.milo.opcua.sdk.core.Reference;
import org.eclipse.milo.opcua.sdk.server.methods.AbstractMethodInvocationHandler.InvocationContext;
import org.eclipse.milo.opcua.sdk.server.nodes.UaObjectNode;
import org.eclipse.milo.opcua.sdk.test.AbstractClientServerTest;
import org.eclipse.milo.opcua.sdk.test.EventTestSupport;
import org.eclipse.milo.opcua.sdk.test.TestNamespace;
import org.eclipse.milo.opcua.stack.core.NodeIds;
import org.eclipse.milo.opcua.stack.core.StatusCodes;
import org.eclipse.milo.opcua.stack.core.UaException;
import org.eclipse.milo.opcua.stack.core.types.builtin.ByteString;
import org.eclipse.milo.opcua.stack.core.types.builtin.DataValue;
import org.eclipse.milo.opcua.stack.core.types.builtin.LocalizedText;
import org.eclipse.milo.opcua.stack.core.types.builtin.NodeId;
import org.eclipse.milo.opcua.stack.core.types.builtin.StatusCode;
import org.eclipse.milo.opcua.stack.core.types.builtin.Variant;
import org.eclipse.milo.opcua.stack.core.types.enumerated.TimestampsToReturn;
import org.eclipse.milo.opcua.stack.core.types.structured.CallMethodRequest;
import org.eclipse.milo.opcua.stack.core.types.structured.CallMethodResult;
import org.eclipse.milo.opcua.stack.core.types.structured.CallResponse;
import org.eclipse.milo.opcua.stack.core.types.structured.EventFilter;
import org.jspecify.annotations.Nullable;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

/**
 * Client-visible tests for the WP2 condition method contract: the five condition methods through
 * both dispatch paths (instance MethodId and ns=0 type-declaration MethodId), the Part 9 Table 137
 * status codes, disabled semantics, the interceptor, and ClientUserId capture.
 */
public class ConditionMethodsTest extends AbstractClientServerTest {

  /** Severity of all events generated by the test condition; the where clause matches on it. */
  private static final int TEST_SEVERITY = 555;

  private AcknowledgeableCondition condition;
  private NodeId conditionId;

  @Override
  protected void customizeClientConfig(OpcUaClientConfigBuilder configBuilder) {
    configBuilder.setIdentityProvider(new UsernameProvider("user1", "password"));
  }

  @Override
  protected void configureTestNamespace(TestNamespace namespace) {
    namespace.configure(
        (context, nodeManager) -> {
          var source =
              new UaObjectNode(
                  context,
                  newNodeId("ConditionMethodsTest/Source"),
                  newQualifiedName("ConditionMethodsTest/Source"),
                  LocalizedText.english("ConditionMethodsTest/Source"),
                  LocalizedText.NULL_VALUE,
                  uint(0),
                  uint(0),
                  ubyte(0));

          source.addReference(
              new Reference(
                  source.getNodeId(),
                  NodeIds.HasTypeDefinition,
                  NodeIds.BaseObjectType.expanded(),
                  true));

          source.addReference(
              new Reference(
                  source.getNodeId(),
                  NodeIds.HasComponent,
                  NodeIds.ObjectsFolder.expanded(),
                  Reference.Direction.INVERSE));

          nodeManager.addNode(source);

          try {
            condition =
                AcknowledgeableCondition.create(
                    context,
                    b ->
                        b.nodeId(newNodeId("ConditionMethodsTest/Condition"))
                            .browseName(newQualifiedName("TestCondition"))
                            .conditionSource(source)
                            .severity(ushort(TEST_SEVERITY))
                            .withConfirm());
          } catch (UaException e) {
            throw new RuntimeException(e);
          }

          server.getConditionManager().register(condition);
          conditionId = condition.getConditionId();
        });
  }

  @BeforeEach
  void resetConditionState() throws Exception {
    condition.setInterceptor(new ConditionMethodInterceptor() {});

    if (!condition.isEnabled()) {
      CallMethodResult result = call(conditionId, NodeIds.ConditionType_Enable);
      assertTrue(requireNonNull(result.getStatusCode()).isGood());
    }

    condition.setConfirmed(true);
    condition.setAcked(true);
  }

  @Test
  void acknowledgeViaInstanceAndTypeDeclarationMethodIds() throws Exception {
    // Via the instance MethodId.
    condition.setAcked(false);
    ByteString eventId = condition.currentBranch().getLastEventId();

    NodeId instanceMethodId =
        requireNonNull(condition.getNode().getAcknowledgeMethodNode()).getNodeId();

    CallMethodResult result =
        call(
            conditionId,
            instanceMethodId,
            new Variant(eventId),
            new Variant(LocalizedText.english("ack via instance")));

    assertTrue(requireNonNull(result.getStatusCode()).isGood());
    assertTrue(condition.isAcked());
    // Acknowledgement opens the confirm cycle; the condition stays retained until confirmed.
    assertFalse(condition.isConfirmed());
    assertTrue(condition.isRetained());
    assertEquals("ack via instance", commentText());

    // Via the ns=0 type-declaration MethodId.
    condition.setConfirmed(true);
    condition.setAcked(false);
    ByteString eventId2 = condition.currentBranch().getLastEventId();

    CallMethodResult result2 =
        call(
            conditionId,
            NodeIds.AcknowledgeableConditionType_Acknowledge,
            new Variant(eventId2),
            new Variant(LocalizedText.english("ack via type")));

    assertTrue(requireNonNull(result2.getStatusCode()).isGood());
    assertTrue(condition.isAcked());
    assertEquals("ack via type", commentText());
  }

  @Test
  void confirmFlowAndAlreadyAckedConfirmedCodes() throws Exception {
    condition.setAcked(false);
    ByteString eventId = condition.currentBranch().getLastEventId();

    CallMethodResult ack =
        call(
            conditionId,
            NodeIds.AcknowledgeableConditionType_Acknowledge,
            new Variant(eventId),
            new Variant(LocalizedText.NULL_VALUE));
    assertTrue(requireNonNull(ack.getStatusCode()).isGood());

    // Acknowledge reports the newly confirmable state with its own EventId. Confirm must use the
    // EventId of a notification whose ConfirmedState/Id was false.
    ByteString confirmableEventId = condition.currentBranch().getLastEventId();

    CallMethodResult ackAgain =
        call(
            conditionId,
            NodeIds.AcknowledgeableConditionType_Acknowledge,
            new Variant(eventId),
            new Variant(LocalizedText.NULL_VALUE));
    assertEquals(
        StatusCode.of(StatusCodes.Bad_ConditionBranchAlreadyAcked), ackAgain.getStatusCode());

    CallMethodResult confirm =
        call(
            conditionId,
            NodeIds.AcknowledgeableConditionType_Confirm,
            new Variant(confirmableEventId),
            new Variant(LocalizedText.NULL_VALUE));
    assertTrue(requireNonNull(confirm.getStatusCode()).isGood());
    assertTrue(condition.isConfirmed());
    assertFalse(condition.isRetained());

    // Already-confirmed error observed through the instance MethodId (C4 both paths).
    NodeId instanceConfirmId =
        requireNonNull(condition.getNode().getConfirmMethodNode()).getNodeId();

    CallMethodResult confirmAgain =
        call(
            conditionId,
            instanceConfirmId,
            new Variant(confirmableEventId),
            new Variant(LocalizedText.NULL_VALUE));
    assertEquals(
        StatusCode.of(StatusCodes.Bad_ConditionBranchAlreadyConfirmed),
        confirmAgain.getStatusCode());
  }

  @Test
  void addCommentBothPathsNullConventionAndEventIdUnknown() throws Exception {
    condition.setAcked(false);
    ByteString eventId = condition.currentBranch().getLastEventId();

    NodeId instanceMethodId =
        requireNonNull(condition.getNode().getAddCommentMethodNode()).getNodeId();

    CallMethodResult viaInstance =
        call(
            conditionId,
            instanceMethodId,
            new Variant(eventId),
            new Variant(LocalizedText.english("comment 1")));
    assertTrue(requireNonNull(viaInstance.getStatusCode()).isGood());
    assertEquals("comment 1", commentText());

    CallMethodResult viaType =
        call(
            conditionId,
            NodeIds.ConditionType_AddComment,
            new Variant(eventId),
            new Variant(LocalizedText.english("comment 2")));
    assertTrue(requireNonNull(viaType.getStatusCode()).isGood());
    assertEquals("comment 2", commentText());

    // Unlike Acknowledge and Confirm, AddComment rejects a NULL comment (§5.5.6).
    CallMethodResult nullComment =
        call(
            conditionId,
            NodeIds.ConditionType_AddComment,
            new Variant(eventId),
            new Variant(LocalizedText.NULL_VALUE));
    assertEquals(StatusCode.of(StatusCodes.Bad_InvalidArgument), nullComment.getStatusCode());
    assertEquals("comment 2", commentText());

    CallMethodResult unknown =
        call(
            conditionId,
            NodeIds.ConditionType_AddComment,
            new Variant(ByteString.of(new byte[] {9, 9, 9})),
            new Variant(LocalizedText.english("comment 3")));
    assertEquals(StatusCode.of(StatusCodes.Bad_EventIdUnknown), unknown.getStatusCode());
    assertEquals("comment 2", commentText());
  }

  @Test
  void eventIdStateAssociationPreventsCrossCycleAcknowledgeAndConfirm() throws Exception {
    // Complete one acknowledgement cycle, then open another while the first EventId is still in
    // the bounded acceptance window.
    condition.setAcked(false);
    ByteString oldAcknowledgeEventId = condition.currentBranch().getLastEventId();
    condition.setAcked(true);
    condition.setAcked(false);

    assertTrue(condition.findBranch(oldAcknowledgeEventId).isPresent());

    CallMethodResult oldAcknowledge =
        call(
            conditionId,
            NodeIds.AcknowledgeableConditionType_Acknowledge,
            new Variant(oldAcknowledgeEventId),
            new Variant(LocalizedText.NULL_VALUE));

    assertEquals(
        StatusCode.of(StatusCodes.Bad_ConditionBranchAlreadyAcked), oldAcknowledge.getStatusCode());
    assertFalse(
        condition.isAcked(), "an EventId from an older cycle must not acknowledge the new state");

    ByteString currentAcknowledgeEventId = condition.currentBranch().getLastEventId();
    CallMethodResult currentAcknowledge =
        call(
            conditionId,
            NodeIds.AcknowledgeableConditionType_Acknowledge,
            new Variant(currentAcknowledgeEventId),
            new Variant(LocalizedText.NULL_VALUE));

    assertTrue(requireNonNull(currentAcknowledge.getStatusCode()).isGood());
    ByteString oldConfirmEventId = condition.currentBranch().getLastEventId();

    CallMethodResult firstConfirm =
        call(
            conditionId,
            NodeIds.AcknowledgeableConditionType_Confirm,
            new Variant(oldConfirmEventId),
            new Variant(LocalizedText.NULL_VALUE));
    assertTrue(requireNonNull(firstConfirm.getStatusCode()).isGood());

    // A new acknowledgement opens a new confirmation cycle. The EventId from the completed cycle
    // is still known, but it must not confirm this newer state.
    condition.setAcked(false);
    ByteString newAcknowledgeEventId = condition.currentBranch().getLastEventId();
    CallMethodResult newAcknowledge =
        call(
            conditionId,
            NodeIds.AcknowledgeableConditionType_Acknowledge,
            new Variant(newAcknowledgeEventId),
            new Variant(LocalizedText.NULL_VALUE));
    assertTrue(requireNonNull(newAcknowledge.getStatusCode()).isGood());
    assertFalse(condition.isConfirmed());
    assertTrue(condition.findBranch(oldConfirmEventId).isPresent());

    CallMethodResult oldConfirm =
        call(
            conditionId,
            NodeIds.AcknowledgeableConditionType_Confirm,
            new Variant(oldConfirmEventId),
            new Variant(LocalizedText.NULL_VALUE));

    assertEquals(
        StatusCode.of(StatusCodes.Bad_ConditionBranchAlreadyConfirmed), oldConfirm.getStatusCode());
    assertFalse(
        condition.isConfirmed(), "an EventId from an older cycle must not confirm the new state");
  }

  @Test
  void nullAddCommentReturnsInvalidArgumentWithoutMutationOrEvent() throws Exception {
    condition.setComment(LocalizedText.english("existing"), "original-user");

    var subscription = new OpcUaSubscription(client);
    subscription.create();

    try {
      List<Variant[]> events = monitorEvents(subscription);

      condition.setAcked(false);
      awaitEvent(
          events, "initial unacknowledged event", e -> "Unacknowledged".equals(messageOf(e)));
      events.clear();

      ByteString eventId = condition.currentBranch().getLastEventId();
      CallMethodResult result =
          call(
              conditionId,
              NodeIds.ConditionType_AddComment,
              new Variant(eventId),
              new Variant(LocalizedText.NULL_VALUE));

      assertEquals(StatusCode.of(StatusCodes.Bad_InvalidArgument), result.getStatusCode());
      assertEquals("existing", commentText());
      assertEquals("original-user", condition.getNode().getClientUserId());
      EventTestSupport.assertNoEvent(events, "NULL AddComment condition event", event -> true);
    } finally {
      subscription.delete();
    }
  }

  @Test
  void clientUserIdCapturedFromSession() throws Exception {
    condition.setAcked(false);
    ByteString eventId = condition.currentBranch().getLastEventId();

    CallMethodResult result =
        call(
            conditionId,
            NodeIds.AcknowledgeableConditionType_Acknowledge,
            new Variant(eventId),
            new Variant(LocalizedText.english("attributed")));

    assertTrue(requireNonNull(result.getStatusCode()).isGood());
    assertEquals("user1", condition.getNode().getClientUserId());
  }

  @Test
  void enableDisableCodesAndDisabledMethodGating() throws Exception {
    CallMethodResult alreadyEnabled = call(conditionId, NodeIds.ConditionType_Enable);
    assertEquals(
        StatusCode.of(StatusCodes.Bad_ConditionAlreadyEnabled), alreadyEnabled.getStatusCode());

    NodeId instanceDisableId =
        requireNonNull(condition.getNode().getDisableMethodNode()).getNodeId();

    CallMethodResult disable = call(conditionId, instanceDisableId);
    assertTrue(requireNonNull(disable.getStatusCode()).isGood());
    assertFalse(condition.isEnabled());

    CallMethodResult alreadyDisabled = call(conditionId, NodeIds.ConditionType_Disable);
    assertEquals(
        StatusCode.of(StatusCodes.Bad_ConditionAlreadyDisabled), alreadyDisabled.getStatusCode());

    // State-changing methods are gated while disabled.
    CallMethodResult ackWhileDisabled =
        call(
            conditionId,
            NodeIds.AcknowledgeableConditionType_Acknowledge,
            new Variant(ByteString.of(new byte[] {1})),
            new Variant(LocalizedText.NULL_VALUE));
    assertEquals(
        StatusCode.of(StatusCodes.Bad_ConditionDisabled), ackWhileDisabled.getStatusCode());

    CallMethodResult commentWhileDisabled =
        call(
            conditionId,
            NodeIds.ConditionType_AddComment,
            new Variant(ByteString.of(new byte[] {1})),
            new Variant(LocalizedText.NULL_VALUE));
    assertEquals(
        StatusCode.of(StatusCodes.Bad_ConditionDisabled), commentWhileDisabled.getStatusCode());

    NodeId instanceEnableId = requireNonNull(condition.getNode().getEnableMethodNode()).getNodeId();

    CallMethodResult enable = call(conditionId, instanceEnableId);
    assertTrue(requireNonNull(enable.getStatusCode()).isGood());
    assertTrue(condition.isEnabled());
  }

  @Test
  void disableRetractionDisabledReadsAndEnableReassertion() throws Exception {
    var subscription = new OpcUaSubscription(client);
    subscription.create();

    try {
      List<Variant[]> events = monitorEvents(subscription);

      condition.setAcked(false);
      awaitEvent(
          events,
          "Unacknowledged with Retain=true",
          e -> "Unacknowledged".equals(messageOf(e)) && retainOf(e));

      // Disable: the single Retain true→false retraction event (§5.5.2).
      CallMethodResult disable = call(conditionId, NodeIds.ConditionType_Disable);
      assertTrue(requireNonNull(disable.getStatusCode()).isGood());

      awaitEvent(
          events,
          "Disabled retraction with Retain=false",
          e -> "Disabled".equals(messageOf(e)) && !retainOf(e));

      // Condition variables read Bad_ConditionDisabled; EnabledState stays readable.
      NodeId qualityNodeId = requireNonNull(condition.getNode().getQualityNode()).getNodeId();
      NodeId ackedStateNodeId = requireNonNull(condition.getNode().getAckedStateNode()).getNodeId();
      NodeId enabledStateNodeId =
          requireNonNull(condition.getNode().getEnabledStateNode()).getNodeId();

      assertEquals(
          StatusCode.of(StatusCodes.Bad_ConditionDisabled),
          readValue(qualityNodeId).getStatusCode());
      assertEquals(
          StatusCode.of(StatusCodes.Bad_ConditionDisabled),
          readValue(ackedStateNodeId).getStatusCode());

      DataValue enabledState = readValue(enabledStateNodeId);
      assertTrue(requireNonNull(enabledState.getStatusCode()).isGood());
      assertEquals(
          "Disabled", ((LocalizedText) requireNonNull(enabledState.value().value())).text());

      // Enable: per-branch re-assertion; the trunk is still unacknowledged, so Retain is true.
      CallMethodResult enable = call(conditionId, NodeIds.ConditionType_Enable);
      assertTrue(requireNonNull(enable.getStatusCode()).isGood());

      awaitEvent(
          events,
          "Enabled re-assertion with Retain=true",
          e -> "Enabled".equals(messageOf(e)) && retainOf(e));

      // Underlying values survived disablement and read Good again.
      assertTrue(requireNonNull(readValue(qualityNodeId).getStatusCode()).isGood());
      assertTrue(requireNonNull(readValue(ackedStateNodeId).getStatusCode()).isGood());
    } finally {
      subscription.delete();
    }
  }

  @Test
  void interceptorVetoHandledAndRuntimeException() throws Exception {
    condition.setAcked(false);
    ByteString eventId = condition.currentBranch().getLastEventId();
    String commentBefore = commentText();

    // Veto with a specific code: state untouched.
    condition.setInterceptor(
        new ConditionMethodInterceptor() {
          @Override
          public Outcome onAcknowledge(
              InvocationContext context, ConditionBranch branch, @Nullable LocalizedText comment)
              throws UaException {
            throw new UaException(StatusCodes.Bad_UserAccessDenied);
          }
        });

    CallMethodResult vetoed = acknowledge(eventId, "vetoed");
    assertEquals(StatusCode.of(StatusCodes.Bad_UserAccessDenied), vetoed.getStatusCode());
    assertFalse(condition.isAcked());
    assertEquals(commentBefore, commentText());

    // HANDLED suppresses the defaults; the call succeeds with state untouched.
    condition.setInterceptor(
        new ConditionMethodInterceptor() {
          @Override
          public Outcome onAcknowledge(
              InvocationContext context, ConditionBranch branch, @Nullable LocalizedText comment) {
            return Outcome.HANDLED;
          }
        });

    CallMethodResult handled = acknowledge(eventId, "handled");
    assertTrue(requireNonNull(handled.getStatusCode()).isGood());
    assertFalse(condition.isAcked());
    assertEquals(commentBefore, commentText());

    // Unexpected RuntimeException maps to Bad_InternalError; state untouched.
    condition.setInterceptor(
        new ConditionMethodInterceptor() {
          @Override
          public Outcome onAcknowledge(
              InvocationContext context, ConditionBranch branch, @Nullable LocalizedText comment) {
            throw new IllegalStateException("interceptor failure");
          }
        });

    CallMethodResult internalError = acknowledge(eventId, "boom");
    assertEquals(StatusCode.of(StatusCodes.Bad_InternalError), internalError.getStatusCode());
    assertFalse(condition.isAcked());

    // Clean PROCEED applies the defaults.
    condition.setInterceptor(new ConditionMethodInterceptor() {});

    CallMethodResult proceeded = acknowledge(eventId, "proceeded");
    assertTrue(requireNonNull(proceeded.getStatusCode()).isGood());
    assertTrue(condition.isAcked());
    assertEquals("proceeded", commentText());
  }

  @Test
  void rapidTransitionsDeliverInternallyConsistentNotifications() throws Exception {
    var subscription = new OpcUaSubscription(client);
    subscription.create();

    try {
      List<Variant[]> events = monitorEvents(subscription);

      for (int i = 0; i < 10; i++) {
        condition.setAcked(false);
        condition.setAcked(true);
      }

      long deadline = System.currentTimeMillis() + 5_000;
      while (events.size() < 20 && System.currentTimeMillis() < deadline) {
        //noinspection BusyWait
        Thread.sleep(50);
      }
      assertEquals(20, events.size());

      // Each notification's fields were extracted under the condition lock and must be
      // internally consistent: Message, AckedState/Id, and Retain agree (A2 evidence).
      for (Variant[] eventFields : events) {
        String message = messageOf(eventFields);
        boolean ackedId = (Boolean) requireNonNull(eventFields[2].value());
        boolean retain = retainOf(eventFields);

        if ("Unacknowledged".equals(message)) {
          assertFalse(ackedId, "Unacknowledged event must carry AckedState/Id=false");
          assertTrue(retain, "Unacknowledged event must carry Retain=true");
        } else if ("Acknowledged".equals(message)) {
          assertTrue(ackedId, "Acknowledged event must carry AckedState/Id=true");
          assertFalse(retain, "Acknowledged event must carry Retain=false");
        } else {
          fail("unexpected event message: " + message);
        }
      }
    } finally {
      subscription.delete();
    }
  }

  private CallMethodResult acknowledge(ByteString eventId, String comment) throws Exception {
    return call(
        conditionId,
        NodeIds.AcknowledgeableConditionType_Acknowledge,
        new Variant(eventId),
        new Variant(LocalizedText.english(comment)));
  }

  private CallMethodResult call(NodeId objectId, NodeId methodId, Variant... inputs)
      throws Exception {

    CallResponse response = client.call(List.of(new CallMethodRequest(objectId, methodId, inputs)));

    return requireNonNull(response.getResults())[0];
  }

  private DataValue readValue(NodeId nodeId) throws Exception {
    return client.readValue(0.0, TimestampsToReturn.Both, nodeId);
  }

  private @Nullable String commentText() {
    LocalizedText comment = condition.getNode().getComment();
    return comment != null ? comment.text() : null;
  }

  /**
   * Monitor events on the Server Object, selecting [Message, Severity, AckedState/Id, Retain] and
   * matching only events with Severity == {@link #TEST_SEVERITY}.
   */
  private List<Variant[]> monitorEvents(OpcUaSubscription subscription) throws Exception {
    EventFilter eventFilter =
        EventTestSupport.severityEventFilter(
            TEST_SEVERITY,
            EventTestSupport.eventField(NodeIds.BaseEventType, "Message"),
            EventTestSupport.eventField(NodeIds.BaseEventType, "Severity"),
            EventTestSupport.eventField(NodeIds.AcknowledgeableConditionType, "AckedState", "Id"),
            EventTestSupport.eventField(NodeIds.ConditionType, "Retain"));

    return EventTestSupport.monitorEvents(subscription, NodeIds.Server, eventFilter);
  }

  private static @Nullable String messageOf(Variant[] eventFields) {
    return eventFields[0].value() instanceof LocalizedText text ? text.text() : null;
  }

  private static boolean retainOf(Variant[] eventFields) {
    return Boolean.TRUE.equals(eventFields[3].value());
  }

  private static void awaitEvent(
      List<Variant[]> events, String description, Predicate<Variant[]> predicate)
      throws InterruptedException {
    EventTestSupport.awaitEvent(events, description, predicate);
  }
}
