/*
 * Copyright (c) 2026 the Eclipse Milo Authors
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 */

package org.eclipse.milo.opcua.sdk.server.conditions;

import static java.util.Objects.requireNonNull;
import static org.eclipse.milo.opcua.stack.core.types.builtin.unsigned.Unsigned.ubyte;
import static org.eclipse.milo.opcua.stack.core.types.builtin.unsigned.Unsigned.uint;
import static org.eclipse.milo.opcua.stack.core.types.builtin.unsigned.Unsigned.ushort;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.time.Duration;
import java.time.Instant;
import java.util.List;
import java.util.Set;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicReference;
import org.eclipse.milo.opcua.sdk.client.subscriptions.OpcUaSubscription;
import org.eclipse.milo.opcua.sdk.core.Reference;
import org.eclipse.milo.opcua.sdk.server.nodes.UaNodeContext;
import org.eclipse.milo.opcua.sdk.server.nodes.UaObjectNode;
import org.eclipse.milo.opcua.sdk.test.AbstractClientServerTest;
import org.eclipse.milo.opcua.sdk.test.EventTestSupport;
import org.eclipse.milo.opcua.sdk.test.TestNamespace;
import org.eclipse.milo.opcua.stack.core.AttributeId;
import org.eclipse.milo.opcua.stack.core.NodeIds;
import org.eclipse.milo.opcua.stack.core.StatusCodes;
import org.eclipse.milo.opcua.stack.core.UaException;
import org.eclipse.milo.opcua.stack.core.encoding.DefaultEncodingContext;
import org.eclipse.milo.opcua.stack.core.types.builtin.ByteString;
import org.eclipse.milo.opcua.stack.core.types.builtin.DateTime;
import org.eclipse.milo.opcua.stack.core.types.builtin.ExtensionObject;
import org.eclipse.milo.opcua.stack.core.types.builtin.LocalizedText;
import org.eclipse.milo.opcua.stack.core.types.builtin.NodeId;
import org.eclipse.milo.opcua.stack.core.types.builtin.QualifiedName;
import org.eclipse.milo.opcua.stack.core.types.builtin.StatusCode;
import org.eclipse.milo.opcua.stack.core.types.builtin.Variant;
import org.eclipse.milo.opcua.stack.core.types.enumerated.FilterOperator;
import org.eclipse.milo.opcua.stack.core.types.structured.CallMethodRequest;
import org.eclipse.milo.opcua.stack.core.types.structured.CallMethodResult;
import org.eclipse.milo.opcua.stack.core.types.structured.CallResponse;
import org.eclipse.milo.opcua.stack.core.types.structured.ContentFilter;
import org.eclipse.milo.opcua.stack.core.types.structured.ContentFilterElement;
import org.eclipse.milo.opcua.stack.core.types.structured.EventFilter;
import org.eclipse.milo.opcua.stack.core.types.structured.LiteralOperand;
import org.eclipse.milo.opcua.stack.core.types.structured.SimpleAttributeOperand;
import org.jspecify.annotations.Nullable;
import org.junit.jupiter.api.Test;

/**
 * Client-visible tests for the WP7 snapshot/restore contract (Part 9 §4.12): a captured
 * active/shelved limit alarm round-trips onto a fresh instance whose restored branch replays via
 * ConditionRefresh with the original EventId/Time and accepts that EventId for Acknowledge; restore
 * is silent and rejected once the Condition is live; absent snapshot fields take the §4.12 recovery
 * defaults; and a shelve deadline that passed during downtime unshelves on first touch.
 *
 * <p>Also covered: a Retained recovery branch with no captured event identity mints an
 * acknowledgeable EventId at first refresh replay (which seals the pre-live restore window),
 * repeated restore replaces rather than accumulates subtype state, and capture under concurrent
 * load always observes one lock-consistent whole-state combination.
 */
public class ConditionSnapshotTest extends AbstractClientServerTest {

  /** Severity of all events generated by the round-trip alarms; the where clause matches on it. */
  private static final int TEST_SEVERITY = 613;

  /** MaxTimeShelved configured on the shelvable alarms, in milliseconds. */
  private static final double MAX_TIME_SHELVED_MILLIS = 300_000.0;

  private UaNodeContext nodeContext;
  private UaObjectNode source;
  private ExclusiveLevelAlarm originalAlarm;

  @Override
  protected void configureTestNamespace(TestNamespace namespace) {
    namespace.configure(
        (context, nodeManager) -> {
          nodeContext = context;

          source =
              new UaObjectNode(
                  context,
                  newNodeId("ConditionSnapshotTest/Source"),
                  newQualifiedName("ConditionSnapshotTest/Source"),
                  LocalizedText.english("ConditionSnapshotTest/Source"),
                  LocalizedText.NULL_VALUE,
                  uint(0),
                  uint(0),
                  ubyte(0));

          source.addReference(
              new Reference(
                  source.getNodeId(),
                  NodeIds.HasTypeDefinition,
                  NodeIds.BaseObjectType.expanded(),
                  true));

          source.addReference(
              new Reference(
                  source.getNodeId(),
                  NodeIds.HasComponent,
                  NodeIds.ObjectsFolder.expanded(),
                  Reference.Direction.INVERSE));

          nodeManager.addNode(source);

          try {
            originalAlarm =
                ExclusiveLevelAlarm.create(
                    context,
                    b ->
                        b.nodeId(newNodeId("ConditionSnapshotTest/Original"))
                            .browseName(newQualifiedName("SnapshotOriginal"))
                            .conditionSource(source)
                            .severity(ushort(TEST_SEVERITY))
                            .withConfirm()
                            .withShelving(Duration.ofMillis((long) MAX_TIME_SHELVED_MILLIS))
                            .highLimit(90.0)
                            .highHighLimit(95.0));
          } catch (UaException e) {
            throw new RuntimeException(e);
          }

          server.getConditionManager().register(originalAlarm);
        });
  }

  @Test
  void capturedAlarmRoundTripsThroughRestoreWithRefreshReplayAndAcknowledge() throws Exception {
    var subscription = new OpcUaSubscription(client);
    subscription.create();

    try {
      List<Variant[]> events =
          EventTestSupport.monitorEvents(subscription, NodeIds.Server, severityFilter());

      // Drive the original alarm into an active/unacked/commented/shelved state.
      originalAlarm.evaluate(92.0);
      originalAlarm.setComment(LocalizedText.english("operator note"), "operator1");

      CallMethodResult shelve =
          call(
              requireNonNull(originalAlarm.getShelvingState()).getNodeId(),
              NodeIds.ShelvedStateMachineType_TimedShelve,
              new Variant(60_000.0));
      assertGood(shelve);
      EventTestSupport.awaitEvent(
          events, "TimedShelved event", e -> "TimedShelved".equals(messageOf(e)));

      ConditionSnapshot snapshot = originalAlarm.captureSnapshot();
      ByteString originalEventId = originalAlarm.currentBranch().getLastEventId();
      DateTime originalEventTime = originalAlarm.currentBranch().getLastEventTime();

      // The captured shape carries the condition, shelving, and branch state.
      assertEquals(Boolean.TRUE, snapshot.enabled());
      assertEquals(LocalizedText.english("operator note"), snapshot.comment());
      assertEquals("operator1", snapshot.clientUserId());
      ConditionSnapshot.ShelvingSnapshot shelving = requireNonNull(snapshot.shelving());
      assertEquals(ShelvedState.TIMED_SHELVED, shelving.state());
      assertNotNull(shelving.unshelveDeadline());
      ConditionSnapshot.BranchSnapshot trunk = snapshot.trunk().orElseThrow();
      assertEquals(Boolean.FALSE, trunk.acked());
      assertEquals(Boolean.TRUE, trunk.active());
      assertEquals(Set.of(ExclusiveLimitState.HIGH), trunk.activeLimits());
      assertTrue(trunk.retained());
      assertEquals(originalEventId, trunk.lastEventId());
      assertEquals(originalEventTime, trunk.lastEventTime());

      // "Restart": the original disappears; a fresh, identically configured instance restores.
      server.getConditionManager().unregister(originalAlarm);

      ExclusiveLevelAlarm restored =
          ExclusiveLevelAlarm.create(
              nodeContext,
              b ->
                  b.nodeId(newNodeId("ConditionSnapshotTest/Restored"))
                      .browseName(newQualifiedName("SnapshotRestored"))
                      .conditionSource(source)
                      .severity(ushort(TEST_SEVERITY))
                      .withConfirm()
                      .withShelving(Duration.ofMillis((long) MAX_TIME_SHELVED_MILLIS))
                      .highLimit(90.0)
                      .highHighLimit(95.0));

      restored.restoreSnapshot(snapshot);
      server.getConditionManager().register(restored);

      assertTrue(restored.isActive());
      assertEquals(ExclusiveLimitState.HIGH, restored.getLimitState());
      assertFalse(restored.isAcked());
      assertTrue(restored.isConfirmed());
      assertTrue(restored.isRetained());
      assertEquals("TimedShelved", currentStateText(restored));
      assertEquals(Boolean.TRUE, restored.getNode().getSuppressedOrShelved());
      assertEquals(LocalizedText.english("operator note"), restored.getNode().getComment());
      assertEquals("operator1", restored.getNode().getClientUserId());
      assertEquals(originalEventId, restored.currentBranch().getLastEventId());
      assertEquals(originalEventTime, restored.currentBranch().getLastEventTime());

      events.clear();

      // A reconnecting client learns the recovered state via refresh replay of the restored
      // branch, carrying the pre-capture EventId/Time and the restored instance's ConditionId.
      assertGood(conditionRefresh(subscription));

      Variant[] replay =
          EventTestSupport.awaitEvent(
              events, "restored branch replay", e -> originalEventId.equals(eventIdOf(e)));
      assertEquals(originalEventTime, replay[4].value(), "replay must carry the original Time");
      assertTrue(retainOf(replay));
      assertEquals(restored.getConditionId(), conditionIdOf(replay));

      // The pre-capture EventId is accepted by Acknowledge, which opens the confirm cycle.
      CallMethodResult acknowledge =
          call(
              restored.getConditionId(),
              NodeIds.AcknowledgeableConditionType_Acknowledge,
              new Variant(originalEventId),
              new Variant(LocalizedText.english("ack after restore")));
      assertGood(acknowledge);
      assertTrue(restored.isAcked());
      assertFalse(restored.isConfirmed());
    } finally {
      subscription.delete();
    }
  }

  @Test
  void restoreIsSilentAndRejectedOnceTheConditionIsLive() throws Exception {
    AlarmCondition alarm =
        AlarmCondition.create(
            nodeContext,
            b ->
                b.nodeId(newNodeId("ConditionSnapshotTest/Silent"))
                    .browseName(newQualifiedName("SnapshotSilent"))
                    .conditionSource(source)
                    .withConfirm()
                    .withShelving(Duration.ofMillis((long) MAX_TIME_SHELVED_MILLIS)));

    var subscription = new OpcUaSubscription(client);
    subscription.create();

    try {
      List<Variant[]> events =
          EventTestSupport.monitorEvents(
              subscription, NodeIds.Server, conditionNameFilter("SnapshotSilent"));

      ByteString preCaptureEventId =
          ByteString.of(new byte[] {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16});
      DateTime preCaptureEventTime = DateTime.now();
      DateTime futureDeadline =
          new DateTime(Instant.ofEpochMilli(System.currentTimeMillis() + 60_000));

      var snapshot =
          new ConditionSnapshot(
              true,
              ushort(200),
              ushort(100),
              StatusCode.GOOD,
              LocalizedText.english("recovered comment"),
              "operator1",
              new ConditionSnapshot.ShelvingSnapshot(ShelvedState.TIMED_SHELVED, futureDeadline),
              List.of(
                  new ConditionSnapshot.BranchSnapshot(
                      null,
                      false,
                      false,
                      false,
                      Set.of(),
                      true,
                      preCaptureEventId,
                      preCaptureEventTime,
                      List.of(
                          new ConditionSnapshot.AcceptedEventId(
                              preCaptureEventId, false, false, true, true)))));

      alarm.restoreSnapshot(snapshot);

      // Restore applied state...
      assertFalse(alarm.isAcked());
      assertFalse(alarm.isActive());
      assertEquals("TimedShelved", currentStateText(alarm));
      assertEquals(ushort(200), alarm.getNode().getSeverity());
      assertTrue(alarm.findBranch(preCaptureEventId).isPresent());
      assertEquals(preCaptureEventId, alarm.currentBranch().getLastEventId());

      // ...but generated no events and minted no EventIds.
      EventTestSupport.assertNoEvent(events, "event generated by restore", e -> true);

      // The first real transition makes the Condition live; restore is then rejected.
      alarm.setActive(true);
      EventTestSupport.awaitEvent(
          events, "activation after restore", e -> "Active".equals(messageOf(e)));

      assertThrows(IllegalStateException.class, () -> alarm.restoreSnapshot(snapshot));
    } finally {
      subscription.delete();
    }
  }

  @Test
  void emptyAndPartialSnapshotsApplyRecoveryDefaults() throws Exception {
    AlarmCondition alarm =
        AlarmCondition.create(
            nodeContext,
            b ->
                b.nodeId(newNodeId("ConditionSnapshotTest/Defaults"))
                    .browseName(newQualifiedName("SnapshotDefaults"))
                    .conditionSource(source)
                    .withConfirm()
                    .withShelving());

    alarm.restoreSnapshot(ConditionSnapshot.empty());

    // §4.12 recovery defaults: Enabled, Acked=False, Confirmed=False, Unshelved — a recovered
    // condition needs attention, so it is Retained, unlike a freshly created idle one.
    assertTrue(alarm.isEnabled());
    assertFalse(alarm.isAcked());
    assertFalse(alarm.isConfirmed());
    assertFalse(alarm.isActive());
    assertEquals("Unshelved", currentStateText(alarm));
    assertTrue(alarm.isRetained());
    assertEquals(ByteString.NULL_VALUE, alarm.currentBranch().getLastEventId());

    // A partial snapshot applies what it has (disabled) and defaults the rest; disabled pins
    // Retain false.
    AlarmCondition disabled =
        AlarmCondition.create(
            nodeContext,
            b ->
                b.nodeId(newNodeId("ConditionSnapshotTest/DefaultsDisabled"))
                    .browseName(newQualifiedName("SnapshotDefaultsDisabled"))
                    .conditionSource(source)
                    .withConfirm()
                    .withShelving());

    disabled.restoreSnapshot(
        new ConditionSnapshot(false, null, null, null, null, null, null, List.of()));

    assertFalse(disabled.isEnabled());
    assertFalse(disabled.isAcked());
    assertFalse(disabled.isRetained());
  }

  @Test
  void pastShelveDeadlineUnshelvesOnFirstTouchAfterRestore() throws Exception {
    AlarmCondition alarm =
        AlarmCondition.create(
            nodeContext,
            b ->
                b.nodeId(newNodeId("ConditionSnapshotTest/PastDeadline"))
                    .browseName(newQualifiedName("SnapshotPastDeadline"))
                    .conditionSource(source)
                    .withShelving(Duration.ofMillis((long) MAX_TIME_SHELVED_MILLIS)));

    DateTime pastDeadline = new DateTime(Instant.ofEpochMilli(System.currentTimeMillis() - 5_000));

    alarm.restoreSnapshot(
        new ConditionSnapshot(
            null,
            null,
            null,
            null,
            null,
            null,
            new ConditionSnapshot.ShelvingSnapshot(ShelvedState.TIMED_SHELVED, pastDeadline),
            List.of()));

    // Restored as captured: still TimedShelved, with no timer armed for the elapsed deadline.
    assertEquals("TimedShelved", currentStateText(alarm));
    assertEquals(Boolean.TRUE, alarm.getNode().getSuppressedOrShelved());
    assertFalse(requireNonNull(alarm.getShelvingRuntime()).hasExpiryTimerForTesting());

    // The first touch applies lazy expiry before validation: the alarm unshelves, so Unshelve
    // itself reports Bad_ConditionNotShelved (the WP4 lazy-expiry contract).
    CallMethodResult unshelve =
        call(
            requireNonNull(alarm.getShelvingState()).getNodeId(),
            NodeIds.ShelvedStateMachineType_Unshelve);
    assertEquals(StatusCode.of(StatusCodes.Bad_ConditionNotShelved), unshelve.getStatusCode());
    assertEquals("Unshelved", currentStateText(alarm));
    assertEquals(Boolean.FALSE, alarm.getNode().getSuppressedOrShelved());
  }

  @Test
  void emptySnapshotRefreshReplayMintsAcknowledgeableEventIdAndSealsRestore() throws Exception {
    AlarmCondition alarm =
        AlarmCondition.create(
            nodeContext,
            b ->
                b.nodeId(newNodeId("ConditionSnapshotTest/Minted"))
                    .browseName(newQualifiedName("SnapshotMinted"))
                    .conditionSource(source));

    alarm.restoreSnapshot(ConditionSnapshot.empty());
    server.getConditionManager().register(alarm);

    var subscription = new OpcUaSubscription(client);
    subscription.create();

    try {
      List<Variant[]> events =
          EventTestSupport.monitorEvents(
              subscription, NodeIds.Server, conditionNameFilter("SnapshotMinted"));

      // The recovery branch is Retained but has no captured event identity: first refresh replay
      // mints a usable EventId rather than replaying an unacknowledgeable NULL one.
      assertGood(conditionRefresh(subscription));

      // Match on ConditionId: the filter-bypassing RefreshStart/RefreshEnd markers carry an
      // EventId of their own but no ConditionId.
      Variant[] replay =
          EventTestSupport.awaitEvent(
              events, "minted replay", e -> alarm.getConditionId().equals(conditionIdOf(e)));

      ByteString mintedEventId = requireNonNull(eventIdOf(replay));
      assertTrue(mintedEventId.isNotNull());
      assertTrue(retainOf(replay));
      assertEquals(mintedEventId, alarm.currentBranch().getLastEventId());

      CallMethodResult acknowledge =
          call(
              alarm.getConditionId(),
              NodeIds.AcknowledgeableConditionType_Acknowledge,
              new Variant(mintedEventId),
              new Variant(LocalizedText.english("ack minted")));
      assertGood(acknowledge);
      assertTrue(alarm.isAcked());

      // The minted EventId is client-visible: the pre-live restore window is closed.
      assertThrows(
          IllegalStateException.class, () -> alarm.restoreSnapshot(ConditionSnapshot.empty()));
    } finally {
      server.getConditionManager().unregister(alarm);
      subscription.delete();
    }
  }

  @Test
  void repeatedRestoreReplacesShelvingLimitAndActiveState() throws Exception {
    ExclusiveLevelAlarm alarm =
        ExclusiveLevelAlarm.create(
            nodeContext,
            b ->
                b.nodeId(newNodeId("ConditionSnapshotTest/Replaced"))
                    .browseName(newQualifiedName("SnapshotReplaced"))
                    .conditionSource(source)
                    .withShelving(Duration.ofMillis((long) MAX_TIME_SHELVED_MILLIS))
                    .highLimit(90.0)
                    .highHighLimit(95.0));

    ByteString eventId =
        ByteString.of(new byte[] {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16});
    DateTime futureDeadline =
        new DateTime(Instant.ofEpochMilli(System.currentTimeMillis() + 60_000));

    var rich =
        new ConditionSnapshot(
            true,
            ushort(500),
            null,
            null,
            null,
            null,
            new ConditionSnapshot.ShelvingSnapshot(ShelvedState.TIMED_SHELVED, futureDeadline),
            List.of(
                new ConditionSnapshot.BranchSnapshot(
                    null,
                    false,
                    false,
                    true,
                    Set.of(ExclusiveLimitState.HIGH),
                    true,
                    eventId,
                    DateTime.now(),
                    List.of(
                        new ConditionSnapshot.AcceptedEventId(
                            eventId, false, false, true, true)))));

    alarm.restoreSnapshot(rich);
    assertTrue(alarm.isActive());
    assertEquals(ExclusiveLimitState.HIGH, alarm.getLimitState());
    assertEquals("TimedShelved", currentStateText(alarm));
    assertTrue(requireNonNull(alarm.getShelvingRuntime()).hasExpiryTimerForTesting());

    // A later restore replaces every level of state: the empty snapshot's recovery defaults win
    // over the previous restore's shelving, limit machine, active state, and event identity.
    alarm.restoreSnapshot(ConditionSnapshot.empty());
    assertFalse(alarm.isActive());
    assertNull(alarm.getLimitState());
    assertEquals("Unshelved", currentStateText(alarm));
    assertEquals(Boolean.FALSE, alarm.getNode().getSuppressedOrShelved());
    assertFalse(requireNonNull(alarm.getShelvingRuntime()).hasExpiryTimerForTesting());
    assertEquals(ByteString.NULL_VALUE, alarm.currentBranch().getLastEventId());
    assertFalse(alarm.findBranch(eventId).isPresent());

    NonExclusiveLimitAlarm nonExclusive =
        NonExclusiveLimitAlarm.create(
            nodeContext,
            b ->
                b.nodeId(newNodeId("ConditionSnapshotTest/ReplacedNonExclusive"))
                    .browseName(newQualifiedName("SnapshotReplacedNonExclusive"))
                    .conditionSource(source)
                    .highLimit(90.0)
                    .highHighLimit(95.0));

    var richNonExclusive =
        new ConditionSnapshot(
            true,
            null,
            null,
            null,
            null,
            null,
            null,
            List.of(
                new ConditionSnapshot.BranchSnapshot(
                    null,
                    false,
                    false,
                    true,
                    Set.of(ExclusiveLimitState.HIGH, ExclusiveLimitState.HIGH_HIGH),
                    true,
                    null,
                    null,
                    List.of())));

    nonExclusive.restoreSnapshot(richNonExclusive);
    assertTrue(nonExclusive.isActive());
    assertTrue(nonExclusive.isLimitActive(ExclusiveLimitState.HIGH));
    assertTrue(nonExclusive.isLimitActive(ExclusiveLimitState.HIGH_HIGH));

    // Limits the next snapshot omits go inactive rather than lingering violated.
    nonExclusive.restoreSnapshot(ConditionSnapshot.empty());
    assertFalse(nonExclusive.isActive());
    assertFalse(nonExclusive.isLimitActive(ExclusiveLimitState.HIGH));
    assertFalse(nonExclusive.isLimitActive(ExclusiveLimitState.HIGH_HIGH));
  }

  @Test
  void timedShelvedSnapshotWithoutDeadlineRestoresUnshelved() throws Exception {
    AlarmCondition alarm =
        AlarmCondition.create(
            nodeContext,
            b ->
                b.nodeId(newNodeId("ConditionSnapshotTest/NoDeadline"))
                    .browseName(newQualifiedName("SnapshotNoDeadline"))
                    .conditionSource(source)
                    .withShelving(Duration.ofMillis((long) MAX_TIME_SHELVED_MILLIS)));

    // TimedShelved without its deadline could never expire; it normalizes to the Unshelved
    // recovery default instead of shelving forever.
    alarm.restoreSnapshot(
        new ConditionSnapshot(
            null,
            null,
            null,
            null,
            null,
            null,
            new ConditionSnapshot.ShelvingSnapshot(ShelvedState.TIMED_SHELVED, null),
            List.of()));

    assertEquals("Unshelved", currentStateText(alarm));
    assertEquals(Boolean.FALSE, alarm.getNode().getSuppressedOrShelved());
    assertFalse(requireNonNull(alarm.getShelvingRuntime()).hasExpiryTimerForTesting());
  }

  @Test
  void restoreWithoutConfirmedStateKeepsBranchConfirmed() throws Exception {
    AlarmCondition alarm =
        AlarmCondition.create(
            nodeContext,
            b ->
                b.nodeId(newNodeId("ConditionSnapshotTest/NoConfirm"))
                    .browseName(newQualifiedName("SnapshotNoConfirm"))
                    .conditionSource(source));

    alarm.restoreSnapshot(ConditionSnapshot.empty());

    // Without the optional ConfirmedState the branch invariant is confirmed == true; the §4.12
    // Confirmed=false default applies only where ConfirmedState exists.
    assertTrue(alarm.isConfirmed());
    assertTrue(alarm.currentBranch().isConfirmed());
    assertEquals(Boolean.TRUE, alarm.captureSnapshot().trunk().orElseThrow().confirmed());
  }

  @Test
  void captureUnderLoadObservesAtomicStateAndRestores() throws Exception {
    ExclusiveLevelAlarm alarm =
        ExclusiveLevelAlarm.create(
            nodeContext,
            b ->
                b.nodeId(newNodeId("ConditionSnapshotTest/UnderLoad"))
                    .browseName(newQualifiedName("SnapshotUnderLoad"))
                    .conditionSource(source)
                    .highLimit(90.0)
                    .highHighLimit(95.0));

    int iterations = 200;
    var start = new CountDownLatch(1);
    var failure = new AtomicReference<Throwable>();

    Thread evaluator =
        new Thread(
            () -> {
              try {
                start.await();
                for (int i = 0; i < iterations; i++) {
                  double value =
                      switch (i % 3) {
                        case 0 -> 92.0;
                        case 1 -> 96.0;
                        default -> 10.0;
                      };
                  alarm.evaluate(value);
                }
              } catch (Throwable e) {
                failure.set(e);
              }
            },
            "snapshot-under-load-evaluator");

    Thread acknowledger =
        new Thread(
            () -> {
              try {
                start.await();
                for (int i = 0; i < iterations; i++) {
                  alarm.setAcked(true);
                }
              } catch (Throwable e) {
                failure.set(e);
              }
            },
            "snapshot-under-load-acknowledger");

    evaluator.start();
    acknowledger.start();
    start.countDown();

    // Capture continuously while both mutators run: every snapshot must be a legal whole-state
    // combination, i.e. one lock-consistent cut, never a torn mix of two transitions.
    long deadline = System.nanoTime() + TimeUnit.SECONDS.toNanos(30);
    while ((evaluator.isAlive() || acknowledger.isAlive()) && System.nanoTime() < deadline) {
      assertSnapshotCoherent(alarm.captureSnapshot());
    }

    evaluator.join(10_000);
    acknowledger.join(10_000);
    assertFalse(evaluator.isAlive(), "evaluator did not finish");
    assertFalse(acknowledger.isAlive(), "acknowledger did not finish");
    if (failure.get() != null) {
      throw new AssertionError("mutator thread failed", failure.get());
    }

    // A final capture round-trips onto a fresh, identically configured instance.
    ConditionSnapshot last = alarm.captureSnapshot();
    assertSnapshotCoherent(last);
    ConditionSnapshot.BranchSnapshot trunk = last.trunk().orElseThrow();

    ExclusiveLevelAlarm restored =
        ExclusiveLevelAlarm.create(
            nodeContext,
            b ->
                b.nodeId(newNodeId("ConditionSnapshotTest/UnderLoadRestored"))
                    .browseName(newQualifiedName("SnapshotUnderLoadRestored"))
                    .conditionSource(source)
                    .highLimit(90.0)
                    .highHighLimit(95.0));
    restored.restoreSnapshot(last);

    assertEquals(Boolean.TRUE.equals(trunk.active()), restored.isActive());
    assertEquals(trunk.activeLimits().stream().findFirst().orElse(null), restored.getLimitState());
    assertEquals(Boolean.TRUE.equals(trunk.acked()), restored.isAcked());
    assertEquals(
        trunk.lastEventId() != null ? trunk.lastEventId() : ByteString.NULL_VALUE,
        restored.currentBranch().getLastEventId());
  }

  /**
   * Assert {@code snapshot} is one legal whole-state combination of an enabled exclusive limit
   * alarm without ConfirmedState: active iff exactly one violated limit, Retain follows the {@code
   * ¬acked ∨ active} formula, and an issued last EventId is within the accepted window.
   */
  private static void assertSnapshotCoherent(ConditionSnapshot snapshot) {
    ConditionSnapshot.BranchSnapshot trunk = snapshot.trunk().orElseThrow();

    boolean active = Boolean.TRUE.equals(trunk.active());
    assertEquals(
        active,
        trunk.activeLimits().size() == 1,
        () -> "active=" + active + " but activeLimits=" + trunk.activeLimits());

    boolean acked = Boolean.TRUE.equals(trunk.acked());
    assertEquals(
        !acked || active,
        trunk.retained(),
        () -> "retained=" + trunk.retained() + " but acked=" + acked + ", active=" + active);

    ByteString lastEventId = trunk.lastEventId();
    if (lastEventId != null && lastEventId.isNotNull()) {
      assertTrue(
          trunk.eventIdWindow().stream().anyMatch(e -> e.eventId().equals(lastEventId)),
          "last EventId missing from the accepted-EventId window");
    }
  }

  private CallMethodResult conditionRefresh(OpcUaSubscription subscription) throws Exception {
    return call(
        NodeIds.ConditionType,
        NodeIds.ConditionType_ConditionRefresh,
        new Variant(subscription.getSubscriptionId().orElseThrow()));
  }

  private CallMethodResult call(NodeId objectId, NodeId methodId, Variant... inputs)
      throws Exception {

    CallResponse response = client.call(List.of(new CallMethodRequest(objectId, methodId, inputs)));

    return requireNonNull(response.getResults())[0];
  }

  private static void assertGood(CallMethodResult result) {
    assertTrue(
        requireNonNull(result.getStatusCode()).isGood(),
        () -> "expected Good status but got " + result.getStatusCode());
  }

  private static @Nullable String currentStateText(AlarmCondition alarm) {
    LocalizedText currentState = requireNonNull(alarm.getShelvingState()).getCurrentState();
    return currentState != null ? currentState.text() : null;
  }

  /**
   * An {@link EventFilter} selecting [EventId, EventType, Message, Severity, Time, Retain,
   * ConditionId], matching only events with Severity == {@link #TEST_SEVERITY}.
   */
  private static EventFilter severityFilter() {
    return EventTestSupport.severityEventFilter(TEST_SEVERITY, selectClauses());
  }

  /** Like {@link #severityFilter()}, but matching on ConditionName equality instead. */
  private static EventFilter conditionNameFilter(String conditionName) {
    var whereClause =
        new ContentFilter(
            new ContentFilterElement[] {
              new ContentFilterElement(
                  FilterOperator.Equals,
                  new ExtensionObject[] {
                    ExtensionObject.encode(
                        DefaultEncodingContext.INSTANCE,
                        EventTestSupport.eventField(NodeIds.ConditionType, "ConditionName")),
                    ExtensionObject.encode(
                        DefaultEncodingContext.INSTANCE,
                        new LiteralOperand(new Variant(conditionName)))
                  })
            });

    return new EventFilter(selectClauses(), whereClause);
  }

  private static SimpleAttributeOperand[] selectClauses() {
    return new SimpleAttributeOperand[] {
      EventTestSupport.eventField(NodeIds.BaseEventType, "EventId"),
      EventTestSupport.eventField(NodeIds.BaseEventType, "EventType"),
      EventTestSupport.eventField(NodeIds.BaseEventType, "Message"),
      EventTestSupport.eventField(NodeIds.BaseEventType, "Severity"),
      EventTestSupport.eventField(NodeIds.BaseEventType, "Time"),
      EventTestSupport.eventField(NodeIds.ConditionType, "Retain"),
      // ConditionId: the NodeId attribute of the condition instance itself (Part 9 §5.5.2).
      new SimpleAttributeOperand(
          NodeIds.ConditionType, new QualifiedName[0], AttributeId.NodeId.uid(), null)
    };
  }

  private static @Nullable ByteString eventIdOf(Variant[] eventFields) {
    return eventFields[0].value() instanceof ByteString eventId ? eventId : null;
  }

  private static @Nullable String messageOf(Variant[] eventFields) {
    return eventFields[2].value() instanceof LocalizedText text ? text.text() : null;
  }

  private static boolean retainOf(Variant[] eventFields) {
    return Boolean.TRUE.equals(eventFields[5].value());
  }

  private static @Nullable NodeId conditionIdOf(Variant[] eventFields) {
    return eventFields[6].value() instanceof NodeId nodeId ? nodeId : null;
  }
}
