/*
 * Copyright (c) 2026 the Eclipse Milo Authors
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 */

package org.eclipse.milo.opcua.sdk.server.conditions;

import static java.util.Objects.requireNonNull;
import static org.eclipse.milo.opcua.stack.core.types.builtin.unsigned.Unsigned.ubyte;
import static org.eclipse.milo.opcua.stack.core.types.builtin.unsigned.Unsigned.uint;
import static org.eclipse.milo.opcua.stack.core.types.builtin.unsigned.Unsigned.ushort;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertNotEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.time.Duration;
import java.util.List;
import org.eclipse.milo.opcua.sdk.client.subscriptions.OpcUaSubscription;
import org.eclipse.milo.opcua.sdk.core.Reference;
import org.eclipse.milo.opcua.sdk.server.methods.AbstractMethodInvocationHandler.InvocationContext;
import org.eclipse.milo.opcua.sdk.server.model.objects.ShelvedStateMachineTypeNode;
import org.eclipse.milo.opcua.sdk.server.nodes.UaObjectNode;
import org.eclipse.milo.opcua.sdk.test.AbstractClientServerTest;
import org.eclipse.milo.opcua.sdk.test.EventTestSupport;
import org.eclipse.milo.opcua.sdk.test.TestNamespace;
import org.eclipse.milo.opcua.stack.core.NodeIds;
import org.eclipse.milo.opcua.stack.core.StatusCodes;
import org.eclipse.milo.opcua.stack.core.UaException;
import org.eclipse.milo.opcua.stack.core.types.builtin.ByteString;
import org.eclipse.milo.opcua.stack.core.types.builtin.DataValue;
import org.eclipse.milo.opcua.stack.core.types.builtin.LocalizedText;
import org.eclipse.milo.opcua.stack.core.types.builtin.NodeId;
import org.eclipse.milo.opcua.stack.core.types.builtin.StatusCode;
import org.eclipse.milo.opcua.stack.core.types.builtin.Variant;
import org.eclipse.milo.opcua.stack.core.types.enumerated.TimestampsToReturn;
import org.eclipse.milo.opcua.stack.core.types.structured.CallMethodRequest;
import org.eclipse.milo.opcua.stack.core.types.structured.CallMethodResult;
import org.eclipse.milo.opcua.stack.core.types.structured.CallResponse;
import org.eclipse.milo.opcua.stack.core.types.structured.EventFilter;
import org.jspecify.annotations.Nullable;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

/**
 * Client-visible tests for the WP4 shelving contract: TimedShelve/OneShotShelve/Unshelve
 * transitions and status codes through both dispatch paths, wall-clock and lazy expiry,
 * MaxTimeShelved enforcement, UnshelveTime countdown, one-shot release on the active→inactive
 * transition, and the Q1 pin that events keep flowing while shelved.
 */
public class ConditionShelvingTest extends AbstractClientServerTest {

  /** Severity of all events generated by the test alarm; the where clause matches on it. */
  private static final int TEST_SEVERITY = 557;

  /** MaxTimeShelved configured on the test alarm, in milliseconds. */
  private static final double MAX_TIME_SHELVED_MILLIS = 60_000.0;

  private AlarmCondition alarm;
  private NodeId conditionId;
  private NodeId shelvingStateId;
  private NodeId timedShelveMethodId;
  private NodeId oneShotShelveMethodId;
  private NodeId unshelveMethodId;
  private NodeId unshelveTimeId;

  @Override
  protected void configureTestNamespace(TestNamespace namespace) {
    namespace.configure(
        (context, nodeManager) -> {
          var source =
              new UaObjectNode(
                  context,
                  newNodeId("ConditionShelvingTest/Source"),
                  newQualifiedName("ConditionShelvingTest/Source"),
                  LocalizedText.english("ConditionShelvingTest/Source"),
                  LocalizedText.NULL_VALUE,
                  uint(0),
                  uint(0),
                  ubyte(0));

          source.addReference(
              new Reference(
                  source.getNodeId(),
                  NodeIds.HasTypeDefinition,
                  NodeIds.BaseObjectType.expanded(),
                  true));

          source.addReference(
              new Reference(
                  source.getNodeId(),
                  NodeIds.HasComponent,
                  NodeIds.ObjectsFolder.expanded(),
                  Reference.Direction.INVERSE));

          nodeManager.addNode(source);

          try {
            alarm =
                AlarmCondition.create(
                    context,
                    b ->
                        b.nodeId(newNodeId("ConditionShelvingTest/Alarm"))
                            .browseName(newQualifiedName("TestShelvedAlarm"))
                            .conditionSource(source)
                            .severity(ushort(TEST_SEVERITY))
                            .withShelving(Duration.ofMillis((long) MAX_TIME_SHELVED_MILLIS)));
          } catch (UaException e) {
            throw new RuntimeException(e);
          }

          server.getConditionManager().register(alarm);
          conditionId = alarm.getConditionId();

          ShelvedStateMachineTypeNode shelvingState = requireNonNull(alarm.getShelvingState());
          shelvingStateId = shelvingState.getNodeId();
          timedShelveMethodId =
              requireNonNull(shelvingState.getTimedShelveMethodNode()).getNodeId();
          oneShotShelveMethodId =
              requireNonNull(shelvingState.getOneShotShelveMethodNode()).getNodeId();
          unshelveMethodId = requireNonNull(shelvingState.getUnshelveMethodNode()).getNodeId();
          unshelveTimeId = requireNonNull(shelvingState.getUnshelveTimeNode()).getNodeId();
        });
  }

  @BeforeEach
  void resetAlarmState() throws Exception {
    alarm.setInterceptor(new ConditionMethodInterceptor() {});
    requireNonNull(alarm.getShelvingRuntime()).setExpiryTimerSuppressedForTesting(false);

    // Unshelve if a previous test left the alarm shelved; Bad_ConditionNotShelved is fine.
    call(shelvingStateId, NodeIds.ShelvedStateMachineType_Unshelve);

    alarm.setActive(false);
    alarm.setAcked(true);
  }

  @Test
  void conditionIdDispatchSupportsAllShelvingMethodsAndBothMethodIdForms() throws Exception {
    alarm.setActive(true);

    // Instance TimedShelve MethodId and type-declaration Unshelve MethodId.
    CallMethodResult timedInstance = call(conditionId, timedShelveMethodId, new Variant(30_000.0));
    assertTrue(requireNonNull(timedInstance.getStatusCode()).isGood());
    assertEquals("TimedShelved", currentStateText());

    CallMethodResult unshelveType = call(conditionId, NodeIds.ShelvedStateMachineType_Unshelve);
    assertTrue(requireNonNull(unshelveType.getStatusCode()).isGood());

    // Instance OneShotShelve and Unshelve MethodIds.
    CallMethodResult oneShotInstance = call(conditionId, oneShotShelveMethodId);
    assertTrue(requireNonNull(oneShotInstance.getStatusCode()).isGood());
    assertEquals("OneShotShelved", currentStateText());

    CallMethodResult unshelveInstance = call(conditionId, unshelveMethodId);
    assertTrue(requireNonNull(unshelveInstance.getStatusCode()).isGood());

    // Type-declaration TimedShelve and OneShotShelve MethodIds remain resolvable too.
    CallMethodResult timedType =
        call(conditionId, NodeIds.ShelvedStateMachineType_TimedShelve, new Variant(30_000.0));
    assertTrue(requireNonNull(timedType.getStatusCode()).isGood());

    CallMethodResult oneShotType = call(conditionId, NodeIds.ShelvedStateMachineType_OneShotShelve);
    assertTrue(requireNonNull(oneShotType.getStatusCode()).isGood());
    assertEquals("OneShotShelved", currentStateText());
  }

  @Test
  void timedShelveTransitionsUnshelveTimeCountdownAndWallClockExpiry() throws Exception {
    var subscription = new OpcUaSubscription(client);
    subscription.create();

    try {
      List<Variant[]> events = monitorEvents(subscription);

      alarm.setActive(true);
      EventTestSupport.awaitEvent(events, "activation event", e -> "Active".equals(messageOf(e)));

      // Shelve long enough that the TimedShelved event delivery (up to one ~1s publish cycle) plus
      // CI jitter cannot outrun the deadline before the first UnshelveTime read below.
      CallMethodResult shelve = call(shelvingStateId, timedShelveMethodId, new Variant(5_000.0));
      assertTrue(requireNonNull(shelve.getStatusCode()).isGood());

      EventTestSupport.awaitEvent(
          events,
          "TimedShelved event with SuppressedOrShelved=true",
          e -> "TimedShelved".equals(messageOf(e)) && suppressedOrShelvedOf(e) && retainOf(e));
      assertEquals("TimedShelved", currentStateText());
      assertEquals(Boolean.TRUE, alarm.getNode().getSuppressedOrShelved());

      // UnshelveTime is computed on read and counts down between reads.
      double firstRead = readUnshelveTime();
      assertTrue(firstRead > 0.0, "UnshelveTime should be positive while TimedShelved");
      Thread.sleep(150);
      double secondRead = readUnshelveTime();
      assertTrue(
          secondRead < firstRead,
          "UnshelveTime should count down between reads: " + secondRead + " < " + firstRead);

      // Wall-clock expiry unshelves without any further calls.
      EventTestSupport.awaitEvent(
          events,
          "expiry Unshelved event with SuppressedOrShelved=false",
          e -> "Unshelved".equals(messageOf(e)) && !suppressedOrShelvedOf(e));
      assertEquals("Unshelved", currentStateText());
      assertEquals(Boolean.FALSE, alarm.getNode().getSuppressedOrShelved());
      assertEquals(0.0, readUnshelveTime());
    } finally {
      subscription.delete();
    }
  }

  @Test
  void lazyExpiryAppliesOnNextMethodTouchWhenTimerIsLost() throws Exception {
    alarm.setActive(true);

    CallMethodResult shelve = call(shelvingStateId, timedShelveMethodId, new Variant(500.0));
    assertTrue(requireNonNull(shelve.getStatusCode()).isGood());

    // Suppress the expiry timer: the deadline stays armed but nothing fires on wall clock.
    ShelvingRuntime shelvingRuntime = requireNonNull(alarm.getShelvingRuntime());
    shelvingRuntime.setExpiryTimerSuppressedForTesting(true);
    shelvingRuntime.makeExpiryDueForTesting();

    assertEquals(
        "TimedShelved", currentStateText(), "with the timer lost the state machine must not move");

    // The next method touch applies expiry before validation: the alarm lazily unshelves, so
    // Unshelve itself reports Bad_ConditionNotShelved.
    CallMethodResult unshelve = call(shelvingStateId, NodeIds.ShelvedStateMachineType_Unshelve);
    assertEquals(StatusCode.of(StatusCodes.Bad_ConditionNotShelved), unshelve.getStatusCode());
    assertEquals("Unshelved", currentStateText());
    assertEquals(Boolean.FALSE, alarm.getNode().getSuppressedOrShelved());
  }

  @Test
  void lazyExpiryAppliesOnNextUnshelveTimeReadWhenTimerIsLost() throws Exception {
    alarm.setActive(true);

    CallMethodResult shelve = call(shelvingStateId, timedShelveMethodId, new Variant(30_000.0));
    assertTrue(requireNonNull(shelve.getStatusCode()).isGood());

    ShelvingRuntime shelvingRuntime = requireNonNull(alarm.getShelvingRuntime());
    shelvingRuntime.setExpiryTimerSuppressedForTesting(true);
    shelvingRuntime.makeExpiryDueForTesting();
    ByteString shelvedEventId = alarm.currentBranch().getLastEventId();

    assertEquals(0.0, readUnshelveTime());
    assertEquals("Unshelved", currentStateText());
    assertEquals(Boolean.FALSE, alarm.getNode().getSuppressedOrShelved());
    assertNotEquals(shelvedEventId, alarm.currentBranch().getLastEventId());
  }

  @Test
  void lazyExpiryAppliesOnNextActiveEvaluationTouchWhenTimerIsLost() throws Exception {
    alarm.setActive(true);

    CallMethodResult shelve = call(shelvingStateId, timedShelveMethodId, new Variant(30_000.0));
    assertTrue(requireNonNull(shelve.getStatusCode()).isGood());

    ShelvingRuntime shelvingRuntime = requireNonNull(alarm.getShelvingRuntime());
    shelvingRuntime.setExpiryTimerSuppressedForTesting(true);
    shelvingRuntime.makeExpiryDueForTesting();
    ByteString shelvedEventId = alarm.currentBranch().getLastEventId();

    // Re-evaluating the unchanged active state is still a shelving touch.
    alarm.setActive(true);

    assertTrue(alarm.isActive());
    assertEquals("Unshelved", currentStateText());
    assertEquals(Boolean.FALSE, alarm.getNode().getSuppressedOrShelved());
    assertNotEquals(shelvedEventId, alarm.currentBranch().getLastEventId());
  }

  @Test
  void oneShotShelveReleasesOnInactiveButTimedShelveDoesNot() throws Exception {
    alarm.setActive(true);

    CallMethodResult oneShot = call(shelvingStateId, NodeIds.ShelvedStateMachineType_OneShotShelve);
    assertTrue(requireNonNull(oneShot.getStatusCode()).isGood());
    assertEquals("OneShotShelved", currentStateText());
    assertEquals(Boolean.TRUE, alarm.getNode().getSuppressedOrShelved());

    // The active→inactive transition releases one-shot shelving.
    alarm.setActive(false);
    assertEquals("Unshelved", currentStateText());
    assertEquals(Boolean.FALSE, alarm.getNode().getSuppressedOrShelved());

    // Timed shelving survives deactivation.
    alarm.setActive(true);
    CallMethodResult timed = call(shelvingStateId, timedShelveMethodId, new Variant(30_000.0));
    assertTrue(requireNonNull(timed.getStatusCode()).isGood());

    alarm.setActive(false);
    assertEquals("TimedShelved", currentStateText());
    assertEquals(Boolean.TRUE, alarm.getNode().getSuppressedOrShelved());

    CallMethodResult unshelve = call(shelvingStateId, NodeIds.ShelvedStateMachineType_Unshelve);
    assertTrue(requireNonNull(unshelve.getStatusCode()).isGood());
  }

  @Test
  void shelvingStatusCodesInterceptorAndCrossShelvingTransitions() throws Exception {
    // Interceptor veto: consulted after validation, state untouched.
    alarm.setInterceptor(
        new ConditionMethodInterceptor() {
          @Override
          public Outcome onTimedShelve(InvocationContext context, double shelvingTimeMillis)
              throws UaException {
            throw new UaException(StatusCodes.Bad_UserAccessDenied);
          }
        });

    CallMethodResult vetoed = call(shelvingStateId, timedShelveMethodId, new Variant(30_000.0));
    assertEquals(StatusCode.of(StatusCodes.Bad_UserAccessDenied), vetoed.getStatusCode());
    assertEquals("Unshelved", currentStateText());

    alarm.setInterceptor(new ConditionMethodInterceptor() {});

    // ShelvingTime must be positive and within MaxTimeShelved.
    CallMethodResult tooLong =
        call(shelvingStateId, timedShelveMethodId, new Variant(MAX_TIME_SHELVED_MILLIS + 1.0));
    assertEquals(StatusCode.of(StatusCodes.Bad_ShelvingTimeOutOfRange), tooLong.getStatusCode());

    CallMethodResult zero = call(shelvingStateId, timedShelveMethodId, new Variant(0.0));
    assertEquals(StatusCode.of(StatusCodes.Bad_ShelvingTimeOutOfRange), zero.getStatusCode());

    CallMethodResult notShelved = call(shelvingStateId, NodeIds.ShelvedStateMachineType_Unshelve);
    assertEquals(StatusCode.of(StatusCodes.Bad_ConditionNotShelved), notShelved.getStatusCode());

    // Valid TimedShelve via the instance MethodId; repeating it is Bad_ConditionAlreadyShelved.
    CallMethodResult timed = call(shelvingStateId, timedShelveMethodId, new Variant(30_000.0));
    assertTrue(requireNonNull(timed.getStatusCode()).isGood());

    CallMethodResult timedAgain = call(shelvingStateId, timedShelveMethodId, new Variant(30_000.0));
    assertEquals(
        StatusCode.of(StatusCodes.Bad_ConditionAlreadyShelved), timedAgain.getStatusCode());

    // TimedShelved → OneShotShelved is a valid transition (type-declaration MethodId path).
    CallMethodResult oneShot = call(shelvingStateId, NodeIds.ShelvedStateMachineType_OneShotShelve);
    assertTrue(requireNonNull(oneShot.getStatusCode()).isGood());
    assertEquals("OneShotShelved", currentStateText());

    CallMethodResult oneShotAgain =
        call(shelvingStateId, NodeIds.ShelvedStateMachineType_OneShotShelve);
    assertEquals(
        StatusCode.of(StatusCodes.Bad_ConditionAlreadyShelved), oneShotAgain.getStatusCode());

    // OneShotShelved → TimedShelved is also valid; then unshelve.
    CallMethodResult backToTimed =
        call(shelvingStateId, timedShelveMethodId, new Variant(30_000.0));
    assertTrue(requireNonNull(backToTimed.getStatusCode()).isGood());
    assertEquals("TimedShelved", currentStateText());

    CallMethodResult unshelve = call(shelvingStateId, NodeIds.ShelvedStateMachineType_Unshelve);
    assertTrue(requireNonNull(unshelve.getStatusCode()).isGood());
    assertEquals("Unshelved", currentStateText());
  }

  @Test
  void eventsKeepFlowingWhileShelvedWithSuppressedOrShelvedTrue() throws Exception {
    var subscription = new OpcUaSubscription(client);
    subscription.create();

    try {
      List<Variant[]> events = monitorEvents(subscription);

      alarm.setActive(true);
      EventTestSupport.awaitEvent(
          events,
          "activation before shelving",
          e -> "Active".equals(messageOf(e)) && !suppressedOrShelvedOf(e));

      CallMethodResult oneShot =
          call(shelvingStateId, NodeIds.ShelvedStateMachineType_OneShotShelve);
      assertTrue(requireNonNull(oneShot.getStatusCode()).isGood());
      EventTestSupport.awaitEvent(
          events,
          "OneShotShelved event",
          e -> "OneShotShelved".equals(messageOf(e)) && suppressedOrShelvedOf(e));

      // Q1 pin: the server does not withhold events while shelved — an operator acknowledge is
      // delivered live with SuppressedOrShelved=true in the fields.
      ByteString eventId = alarm.currentBranch().getLastEventId();
      CallMethodResult ack =
          call(
              conditionId,
              NodeIds.AcknowledgeableConditionType_Acknowledge,
              new Variant(eventId),
              new Variant(LocalizedText.NULL_VALUE));
      assertTrue(requireNonNull(ack.getStatusCode()).isGood());

      EventTestSupport.awaitEvent(
          events,
          "acknowledge delivered while shelved",
          e -> "Acknowledged".equals(messageOf(e)) && suppressedOrShelvedOf(e));

      // Deactivation releases the one-shot shelve in the same transition: the retraction event
      // reports both ActiveState=false (via Retain=false here) and SuppressedOrShelved=false.
      alarm.setActive(false);
      EventTestSupport.awaitEvent(
          events,
          "retraction with one-shot release",
          e -> "Inactive".equals(messageOf(e)) && !suppressedOrShelvedOf(e) && !retainOf(e));
      assertEquals("Unshelved", currentStateText());
    } finally {
      subscription.delete();
    }
  }

  private CallMethodResult call(NodeId objectId, NodeId methodId, Variant... inputs)
      throws Exception {

    CallResponse response = client.call(List.of(new CallMethodRequest(objectId, methodId, inputs)));

    return requireNonNull(response.getResults())[0];
  }

  private @Nullable String currentStateText() {
    LocalizedText currentState = requireNonNull(alarm.getShelvingState()).getCurrentState();
    return currentState != null ? currentState.text() : null;
  }

  private double readUnshelveTime() throws Exception {
    DataValue value = client.readValue(0.0, TimestampsToReturn.Both, unshelveTimeId);
    assertTrue(requireNonNull(value.getStatusCode()).isGood());
    return (Double) requireNonNull(value.value().value());
  }

  /**
   * Monitor events on the Server Object, selecting [Message, Severity, SuppressedOrShelved, Retain]
   * and matching only events with Severity == {@link #TEST_SEVERITY}.
   */
  private List<Variant[]> monitorEvents(OpcUaSubscription subscription) throws Exception {
    EventFilter eventFilter =
        EventTestSupport.severityEventFilter(
            TEST_SEVERITY,
            EventTestSupport.eventField(NodeIds.BaseEventType, "Message"),
            EventTestSupport.eventField(NodeIds.BaseEventType, "Severity"),
            EventTestSupport.eventField(NodeIds.AlarmConditionType, "SuppressedOrShelved"),
            EventTestSupport.eventField(NodeIds.ConditionType, "Retain"));

    return EventTestSupport.monitorEvents(subscription, NodeIds.Server, eventFilter);
  }

  private static @Nullable String messageOf(Variant[] eventFields) {
    return eventFields[0].value() instanceof LocalizedText text ? text.text() : null;
  }

  private static boolean suppressedOrShelvedOf(Variant[] eventFields) {
    return Boolean.TRUE.equals(eventFields[2].value());
  }

  private static boolean retainOf(Variant[] eventFields) {
    return Boolean.TRUE.equals(eventFields[3].value());
  }
}
