/*
 * Copyright (c) 2026 the Eclipse Milo Authors
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 */

package org.eclipse.milo.opcua.sdk.server.conditions;

import static java.util.Objects.requireNonNull;
import static org.eclipse.milo.opcua.stack.core.types.builtin.unsigned.Unsigned.ubyte;
import static org.eclipse.milo.opcua.stack.core.types.builtin.unsigned.Unsigned.uint;
import static org.eclipse.milo.opcua.stack.core.types.builtin.unsigned.Unsigned.ushort;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.fail;
import static org.mockito.Mockito.doThrow;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import java.util.List;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.CopyOnWriteArrayList;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;
import java.util.stream.Stream;
import org.eclipse.milo.opcua.sdk.client.OpcUaClient;
import org.eclipse.milo.opcua.sdk.client.subscriptions.OpcUaMonitoredItem;
import org.eclipse.milo.opcua.sdk.client.subscriptions.OpcUaSubscription;
import org.eclipse.milo.opcua.sdk.core.Reference;
import org.eclipse.milo.opcua.sdk.server.EventListener;
import org.eclipse.milo.opcua.sdk.server.Session;
import org.eclipse.milo.opcua.sdk.server.UaNodeManager;
import org.eclipse.milo.opcua.sdk.server.model.objects.AcknowledgeableConditionTypeNode;
import org.eclipse.milo.opcua.sdk.server.model.objects.BaseEventTypeNode;
import org.eclipse.milo.opcua.sdk.server.nodes.UaNodeContext;
import org.eclipse.milo.opcua.sdk.server.nodes.UaObjectNode;
import org.eclipse.milo.opcua.sdk.test.AbstractClientServerTest;
import org.eclipse.milo.opcua.sdk.test.EventTestSupport;
import org.eclipse.milo.opcua.sdk.test.TestClient;
import org.eclipse.milo.opcua.sdk.test.TestNamespace;
import org.eclipse.milo.opcua.stack.core.AttributeId;
import org.eclipse.milo.opcua.stack.core.NodeIds;
import org.eclipse.milo.opcua.stack.core.StatusCodes;
import org.eclipse.milo.opcua.stack.core.UaException;
import org.eclipse.milo.opcua.stack.core.types.builtin.ByteString;
import org.eclipse.milo.opcua.stack.core.types.builtin.DateTime;
import org.eclipse.milo.opcua.stack.core.types.builtin.LocalizedText;
import org.eclipse.milo.opcua.stack.core.types.builtin.NodeId;
import org.eclipse.milo.opcua.stack.core.types.builtin.QualifiedName;
import org.eclipse.milo.opcua.stack.core.types.builtin.StatusCode;
import org.eclipse.milo.opcua.stack.core.types.builtin.Variant;
import org.eclipse.milo.opcua.stack.core.types.builtin.unsigned.UInteger;
import org.eclipse.milo.opcua.stack.core.types.structured.CallMethodRequest;
import org.eclipse.milo.opcua.stack.core.types.structured.CallMethodResult;
import org.eclipse.milo.opcua.stack.core.types.structured.CallResponse;
import org.eclipse.milo.opcua.stack.core.types.structured.EventFilter;
import org.eclipse.milo.opcua.stack.core.types.structured.SimpleAttributeOperand;
import org.jspecify.annotations.Nullable;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

/**
 * Client-visible tests for the WP3 refresh contract (Part 9 §5.5.7, §4.5): per-item
 * filter-bypassing RefreshStart/RefreshEnd markers, Retain-based replay carrying the original
 * EventId/Time, the refresh status codes, ConditionRefresh2 item scoping, subscription isolation,
 * live events during replay, and RefreshRequired after condition-event queue overflow.
 */
public class ConditionRefreshTest extends AbstractClientServerTest {

  /** Severity of all events generated by the test condition; where clauses match on it. */
  private static final int TEST_SEVERITY = 601;

  /** A severity matching nothing the test condition generates. */
  private static final int OTHER_SEVERITY = 602;

  private AcknowledgeableCondition condition;
  private AcknowledgeableCondition conditionB;
  private PausingAcknowledgeableCondition pausingCondition;
  private CleanupFailingCondition cleanupFailingCondition;
  private NodeId conditionId;
  private NodeId areaAId;
  private NodeId areaBId;

  @Override
  protected void configureTestNamespace(TestNamespace namespace) {
    namespace.configure(
        (context, nodeManager) -> {
          UaObjectNode areaA = addObjectNode(context, nodeManager, "AreaA");
          UaObjectNode areaB = addObjectNode(context, nodeManager, "AreaB");
          UaObjectNode sourceA = addObjectNode(context, nodeManager, "AreaA/Source");
          UaObjectNode sourceB = addObjectNode(context, nodeManager, "AreaB/Source");

          nodeManager.addReferences(
              new Reference(
                  areaA.getNodeId(), NodeIds.HasEventSource, sourceA.getNodeId().expanded(), true),
              server.getNamespaceTable());
          nodeManager.addReferences(
              new Reference(
                  areaB.getNodeId(), NodeIds.HasEventSource, sourceB.getNodeId().expanded(), true),
              server.getNamespaceTable());

          namespace.registerEventNotifier(areaA);
          namespace.registerEventNotifier(areaB);
          areaAId = areaA.getNodeId();
          areaBId = areaB.getNodeId();

          try {
            condition =
                AcknowledgeableCondition.create(
                    context,
                    b ->
                        b.nodeId(newNodeId("ConditionRefreshTest/Condition"))
                            .browseName(newQualifiedName("TestRefreshCondition"))
                            .conditionSource(sourceA)
                            .severity(ushort(TEST_SEVERITY))
                            .withConfirm());

            conditionB =
                AcknowledgeableCondition.create(
                    context,
                    b ->
                        b.nodeId(newNodeId("ConditionRefreshTest/ConditionB"))
                            .browseName(newQualifiedName("TestRefreshConditionB"))
                            .conditionSource(sourceB)
                            .severity(ushort(TEST_SEVERITY))
                            .withConfirm());

            AcknowledgeableCondition pausingBase =
                AcknowledgeableCondition.create(
                    context,
                    b ->
                        b.nodeId(newNodeId("ConditionRefreshTest/PausingCondition"))
                            .browseName(newQualifiedName("PausingCondition"))
                            .conditionSource(sourceA)
                            .severity(ushort(TEST_SEVERITY)));
            pausingCondition = new PausingAcknowledgeableCondition(pausingBase.getNode());

            AcknowledgeableCondition cleanupFailingBase =
                AcknowledgeableCondition.create(
                    context,
                    b ->
                        b.nodeId(newNodeId("ConditionRefreshTest/CleanupFailingCondition"))
                            .browseName(newQualifiedName("CleanupFailingCondition"))
                            .conditionSource(sourceA)
                            .severity(ushort(TEST_SEVERITY)));
            cleanupFailingCondition = new CleanupFailingCondition(cleanupFailingBase.getNode());
          } catch (UaException e) {
            throw new RuntimeException(e);
          }

          server.getConditionManager().register(condition);
          server.getConditionManager().register(conditionB);
          server.getConditionManager().register(pausingCondition);
          conditionId = condition.getConditionId();
        });
  }

  private UaObjectNode addObjectNode(
      UaNodeContext context, UaNodeManager nodeManager, String name) {

    var node =
        new UaObjectNode(
            context,
            newNodeId("ConditionRefreshTest/" + name),
            newQualifiedName("ConditionRefreshTest/" + name),
            LocalizedText.english("ConditionRefreshTest/" + name),
            LocalizedText.NULL_VALUE,
            uint(0),
            uint(0),
            ubyte(0));

    node.addReference(
        new Reference(
            node.getNodeId(), NodeIds.HasTypeDefinition, NodeIds.BaseObjectType.expanded(), true));
    node.addReference(
        new Reference(
            node.getNodeId(),
            NodeIds.HasComponent,
            NodeIds.ObjectsFolder.expanded(),
            Reference.Direction.INVERSE));

    nodeManager.addNode(node);

    return node;
  }

  @BeforeEach
  void resetConditionState() {
    pausingCondition.disableSnapshotPause();
    condition.setConfirmed(true);
    condition.setAcked(true);
    conditionB.setConfirmed(true);
    conditionB.setAcked(true);
    pausingCondition.setAcked(true);
  }

  @Test
  void markersBypassFiltersAndRetainedStateReplaysWithOriginalIdentity() throws Exception {
    var subscription = new OpcUaSubscription(client);
    subscription.create();

    try {
      List<Variant[]> matching = monitorEvents(subscription, TEST_SEVERITY);
      List<Variant[]> excluded = monitorEvents(subscription, OTHER_SEVERITY);

      condition.setAcked(false);
      EventTestSupport.awaitEvent(
          matching, "live unacknowledged event", e -> "Unacknowledged".equals(messageOf(e)));
      matching.clear();

      ByteString lastEventId = condition.currentBranch().getLastEventId();
      DateTime lastEventTime = condition.currentBranch().getLastEventTime();

      CallMethodResult result = conditionRefresh(subscription);
      assertGood(result);

      // The item whose where clause matches the condition's events: full bracket plus replay.
      Variant[] start =
          EventTestSupport.awaitEvent(
              matching,
              "RefreshStart marker",
              e -> NodeIds.RefreshStartEventType.equals(eventTypeOf(e)));
      Variant[] replay =
          EventTestSupport.awaitEvent(
              matching, "replayed condition event", e -> lastEventId.equals(eventIdOf(e)));
      Variant[] end =
          EventTestSupport.awaitEvent(
              matching,
              "RefreshEnd marker",
              e -> NodeIds.RefreshEndEventType.equals(eventTypeOf(e)));

      // The replayed state carries the original identity and current retained state.
      assertEquals(lastEventTime, replay[4].value(), "replay must carry the original Time");
      assertEquals("Unacknowledged", messageOf(replay));
      assertTrue(retainOf(replay));
      assertEquals(conditionId, conditionIdOf(replay), "ConditionId must resolve on replay");

      // The bracket is ordered around the replay.
      assertTrue(matching.indexOf(start) < matching.indexOf(replay), "RefreshStart before replay");
      assertTrue(matching.indexOf(replay) < matching.indexOf(end), "replay before RefreshEnd");

      // The item whose where clause excludes everything: markers arrive anyway (§4.5 bypass),
      // replayed events respect the filter.
      Variant[] excludedStart =
          EventTestSupport.awaitEvent(
              excluded,
              "RefreshStart marker on filter-excluded item",
              e -> NodeIds.RefreshStartEventType.equals(eventTypeOf(e)));
      EventTestSupport.awaitEvent(
          excluded,
          "RefreshEnd marker on filter-excluded item",
          e -> NodeIds.RefreshEndEventType.equals(eventTypeOf(e)));
      EventTestSupport.assertNoEvent(
          excluded,
          "replayed event on filter-excluded item",
          e -> lastEventId.equals(eventIdOf(e)));

      // One shared EventId per bracket marker across the subscription's items.
      assertEquals(eventIdOf(start), eventIdOf(excludedStart));
    } finally {
      subscription.delete();
    }
  }

  @Test
  void replayedEventIdIsAcceptedByAcknowledge() throws Exception {
    var subscription = new OpcUaSubscription(client);
    subscription.create();

    try {
      List<Variant[]> events = monitorEvents(subscription, TEST_SEVERITY);

      condition.setAcked(false);
      ByteString lastEventId = condition.currentBranch().getLastEventId();
      events.clear();

      CallMethodResult refresh = conditionRefresh(subscription);
      assertGood(refresh);

      Variant[] replay =
          EventTestSupport.awaitEvent(
              events, "replayed condition event", e -> lastEventId.equals(eventIdOf(e)));

      CallMethodResult acknowledge =
          call(
              conditionId,
              NodeIds.AcknowledgeableConditionType_Acknowledge,
              new Variant(eventIdOf(replay)),
              new Variant(LocalizedText.english("ack after refresh")));

      assertGood(acknowledge);
      assertTrue(condition.isAcked());
    } finally {
      subscription.delete();
    }
  }

  @Test
  void refreshStatusCodes() throws Exception {
    // Unknown subscription id.
    CallMethodResult unknown =
        call(
            NodeIds.ConditionType,
            NodeIds.ConditionType_ConditionRefresh,
            new Variant(uint(Integer.MAX_VALUE)));
    assertEquals(StatusCode.of(StatusCodes.Bad_SubscriptionIdInvalid), unknown.getStatusCode());

    // A subscription with no event monitored items.
    var emptySubscription = new OpcUaSubscription(client);
    emptySubscription.create();
    try {
      CallMethodResult nothingToDo = conditionRefresh(emptySubscription);
      assertEquals(StatusCode.of(StatusCodes.Bad_NothingToDo), nothingToDo.getStatusCode());
    } finally {
      emptySubscription.delete();
    }

    // Another session's subscription id.
    OpcUaClient client2 = TestClient.create(server, configBuilder -> {});
    client2.connect();
    try {
      var foreignSubscription = new OpcUaSubscription(client2);
      foreignSubscription.create();

      CallMethodResult foreign =
          call(
              NodeIds.ConditionType,
              NodeIds.ConditionType_ConditionRefresh,
              new Variant(foreignSubscription.getSubscriptionId().orElseThrow()));
      assertEquals(StatusCode.of(StatusCodes.Bad_UserAccessDenied), foreign.getStatusCode());
    } finally {
      client2.disconnect();
    }

    // ConditionRefresh2 with a monitored item belonging to a different subscription.
    var subscriptionA = new OpcUaSubscription(client);
    subscriptionA.create();
    var subscriptionB = new OpcUaSubscription(client);
    subscriptionB.create();
    try {
      monitorEvents(subscriptionA, TEST_SEVERITY);

      // Item ids are assigned per subscription, so give subscription B a second item: its id has
      // no counterpart in subscription A.
      monitorEvents(subscriptionB, TEST_SEVERITY);

      var eventsB = new CopyOnWriteArrayList<Variant[]>();
      OpcUaMonitoredItem itemB =
          EventTestSupport.createEventItem(
              subscriptionB, NodeIds.Server, eventFilter(TEST_SEVERITY), eventsB);

      CallMethodResult wrongSubscription =
          call(
              NodeIds.ConditionType,
              NodeIds.ConditionType_ConditionRefresh2,
              new Variant(subscriptionA.getSubscriptionId().orElseThrow()),
              new Variant(itemB.getMonitoredItemId().orElseThrow()));
      assertEquals(
          StatusCode.of(StatusCodes.Bad_MonitoredItemIdInvalid), wrongSubscription.getStatusCode());
    } finally {
      subscriptionA.delete();
      subscriptionB.delete();
    }
  }

  @Test
  void conditionRefresh2ScopesToTheNamedItem() throws Exception {
    var subscription = new OpcUaSubscription(client);
    subscription.create();

    try {
      var events1 = new CopyOnWriteArrayList<Variant[]>();
      OpcUaMonitoredItem item1 =
          EventTestSupport.createEventItem(
              subscription, NodeIds.Server, eventFilter(TEST_SEVERITY), events1);

      var events2 = new CopyOnWriteArrayList<Variant[]>();
      EventTestSupport.createEventItem(
          subscription, NodeIds.Server, eventFilter(TEST_SEVERITY), events2);

      condition.setAcked(false);
      ByteString lastEventId = condition.currentBranch().getLastEventId();
      EventTestSupport.awaitEvent(
          events1, "live unacknowledged event on item1", e -> lastEventId.equals(eventIdOf(e)));
      EventTestSupport.awaitEvent(
          events2, "live unacknowledged event on item2", e -> lastEventId.equals(eventIdOf(e)));
      events1.clear();
      events2.clear();

      CallMethodResult result =
          call(
              NodeIds.ConditionType,
              NodeIds.ConditionType_ConditionRefresh2,
              new Variant(subscription.getSubscriptionId().orElseThrow()),
              new Variant(item1.getMonitoredItemId().orElseThrow()));
      assertGood(result);

      EventTestSupport.awaitEvent(
          events1,
          "RefreshStart marker on the named item",
          e -> NodeIds.RefreshStartEventType.equals(eventTypeOf(e)));
      EventTestSupport.awaitEvent(
          events1, "replayed condition event", e -> lastEventId.equals(eventIdOf(e)));
      EventTestSupport.awaitEvent(
          events1,
          "RefreshEnd marker on the named item",
          e -> NodeIds.RefreshEndEventType.equals(eventTypeOf(e)));

      EventTestSupport.assertNoEvent(events2, "refresh traffic on the unnamed item", e -> true);
    } finally {
      subscription.delete();
    }
  }

  @Test
  void refreshReplayPreservesNotifierHierarchyScope() throws Exception {
    var subscription = new OpcUaSubscription(client);
    subscription.create();

    try {
      var areaAEvents = new CopyOnWriteArrayList<Variant[]>();
      OpcUaMonitoredItem areaAItem =
          EventTestSupport.createEventItem(
              subscription, areaAId, eventFilter(TEST_SEVERITY), areaAEvents);

      var areaBEvents = new CopyOnWriteArrayList<Variant[]>();
      EventTestSupport.createEventItem(
          subscription, areaBId, eventFilter(TEST_SEVERITY), areaBEvents);

      condition.setAcked(false);
      conditionB.setAcked(false);
      ByteString eventIdA = condition.currentBranch().getLastEventId();
      ByteString eventIdB = conditionB.currentBranch().getLastEventId();

      EventTestSupport.awaitEvent(
          areaAEvents, "live Area A condition", e -> eventIdA.equals(eventIdOf(e)));
      EventTestSupport.awaitEvent(
          areaBEvents, "live Area B condition", e -> eventIdB.equals(eventIdOf(e)));
      areaAEvents.clear();
      areaBEvents.clear();

      assertGood(conditionRefresh(subscription));

      EventTestSupport.awaitEvent(
          areaAEvents,
          "ConditionRefresh Area A start",
          e -> NodeIds.RefreshStartEventType.equals(eventTypeOf(e)));
      EventTestSupport.awaitEvent(
          areaAEvents, "ConditionRefresh Area A replay", e -> eventIdA.equals(eventIdOf(e)));
      EventTestSupport.awaitEvent(
          areaAEvents,
          "ConditionRefresh Area A end",
          e -> NodeIds.RefreshEndEventType.equals(eventTypeOf(e)));

      EventTestSupport.awaitEvent(
          areaBEvents,
          "ConditionRefresh Area B start",
          e -> NodeIds.RefreshStartEventType.equals(eventTypeOf(e)));
      EventTestSupport.awaitEvent(
          areaBEvents, "ConditionRefresh Area B replay", e -> eventIdB.equals(eventIdOf(e)));
      EventTestSupport.awaitEvent(
          areaBEvents,
          "ConditionRefresh Area B end",
          e -> NodeIds.RefreshEndEventType.equals(eventTypeOf(e)));

      EventTestSupport.assertNoEvent(
          areaAEvents,
          "out-of-scope Area B replay on Area A item",
          e -> eventIdB.equals(eventIdOf(e)));
      EventTestSupport.assertNoEvent(
          areaBEvents,
          "out-of-scope Area A replay on Area B item",
          e -> eventIdA.equals(eventIdOf(e)));

      areaAEvents.clear();
      areaBEvents.clear();

      CallMethodResult refresh2 =
          call(
              NodeIds.ConditionType,
              NodeIds.ConditionType_ConditionRefresh2,
              new Variant(subscription.getSubscriptionId().orElseThrow()),
              new Variant(areaAItem.getMonitoredItemId().orElseThrow()));
      assertGood(refresh2);

      EventTestSupport.awaitEvent(
          areaAEvents,
          "ConditionRefresh2 Area A start",
          e -> NodeIds.RefreshStartEventType.equals(eventTypeOf(e)));
      EventTestSupport.awaitEvent(
          areaAEvents, "ConditionRefresh2 Area A replay", e -> eventIdA.equals(eventIdOf(e)));
      EventTestSupport.awaitEvent(
          areaAEvents,
          "ConditionRefresh2 Area A end",
          e -> NodeIds.RefreshEndEventType.equals(eventTypeOf(e)));
      EventTestSupport.assertNoEvent(
          areaAEvents,
          "ConditionRefresh2 out-of-scope Area B replay",
          e -> eventIdB.equals(eventIdOf(e)));
      EventTestSupport.assertNoEvent(
          areaBEvents, "ConditionRefresh2 traffic on the unnamed Area B item", e -> true);
    } finally {
      subscription.delete();
    }
  }

  @Test
  void otherSubscriptionsSeeNoRefreshTraffic() throws Exception {
    var subscription1 = new OpcUaSubscription(client);
    subscription1.create();
    var subscription2 = new OpcUaSubscription(client);
    subscription2.create();

    try {
      List<Variant[]> events1 = monitorEvents(subscription1, TEST_SEVERITY);
      List<Variant[]> events2 = monitorEvents(subscription2, TEST_SEVERITY);

      condition.setAcked(false);
      ByteString lastEventId = condition.currentBranch().getLastEventId();
      EventTestSupport.awaitEvent(
          events1, "live event on subscription 1", e -> lastEventId.equals(eventIdOf(e)));
      EventTestSupport.awaitEvent(
          events2, "live event on subscription 2", e -> lastEventId.equals(eventIdOf(e)));
      events1.clear();
      events2.clear();

      CallMethodResult result = conditionRefresh(subscription1);
      assertGood(result);

      EventTestSupport.awaitEvent(
          events1,
          "RefreshEnd marker on the refreshed subscription",
          e -> NodeIds.RefreshEndEventType.equals(eventTypeOf(e)));

      EventTestSupport.assertNoEvent(
          events2, "refresh traffic on the other subscription", e -> true);
    } finally {
      subscription1.delete();
      subscription2.delete();
    }
  }

  @Test
  void concurrentRefreshReturnsRefreshInProgressWhileOthersAreAccepted() throws Exception {
    var subscription1 = new OpcUaSubscription(client);
    subscription1.create();
    var subscription2 = new OpcUaSubscription(client);
    subscription2.create();

    var entered = new CountDownLatch(1);
    var release = new CountDownLatch(1);

    // Fired under the Condition's lock: blocking here keeps the lock held, which stalls a refresh
    // at snapshot creation — after its per-subscription guard is engaged, but without touching any
    // subscription or item monitor the publish pipeline uses.
    EventListener blockingListener =
        eventNode -> {
          if (eventNode == condition.getNode()) {
            entered.countDown();
            try {
              release.await(10, TimeUnit.SECONDS);
            } catch (InterruptedException e) {
              Thread.currentThread().interrupt();
            }
          }
        };

    try {
      monitorEvents(subscription1, TEST_SEVERITY);
      monitorEvents(subscription2, TEST_SEVERITY);

      condition.setAcked(false);

      UInteger subscription1Id = subscription1.getSubscriptionId().orElseThrow();
      UInteger subscription2Id = subscription2.getSubscriptionId().orElseThrow();
      Session serverSession = server.getSubscriptions().get(subscription1Id).getSession();

      server.getEventNotifier().register(blockingListener);

      var toggler = new Thread(() -> condition.setAcked(true));
      toggler.start();

      assertTrue(entered.await(5, TimeUnit.SECONDS), "the Condition lock was not engaged in time");

      var firstRefresh = new CompletableFuture<Void>();
      var refreshThread =
          new Thread(
              () -> {
                try {
                  server.getConditionManager().conditionRefresh(serverSession, subscription1Id);
                  firstRefresh.complete(null);
                } catch (Throwable t) {
                  firstRefresh.completeExceptionally(t);
                }
              });
      refreshThread.start();

      // Wait until the refresh is parked at snapshot creation: its guard is engaged from that
      // point until it completes, which the held Condition lock prevents.
      long deadline = System.currentTimeMillis() + 5_000;
      while (!isBlockedCreatingSnapshots(refreshThread)) {
        if (System.currentTimeMillis() > deadline) {
          fail("refresh did not block at snapshot creation");
        }
        //noinspection BusyWait
        Thread.sleep(10);
      }

      // A concurrent refresh of the same subscription is rejected...
      UaException e =
          assertThrows(
              UaException.class,
              () -> server.getConditionManager().conditionRefresh(serverSession, subscription1Id));
      assertEquals(StatusCode.of(StatusCodes.Bad_RefreshInProgress), e.getStatusCode());

      // ...while a refresh of a different subscription is accepted (it serializes on the shared
      // Condition lock but is not rejected by subscription 1's guard).
      var secondRefresh = new CompletableFuture<Void>();
      var refresh2Thread =
          new Thread(
              () -> {
                try {
                  server.getConditionManager().conditionRefresh(serverSession, subscription2Id);
                  secondRefresh.complete(null);
                } catch (Throwable t) {
                  secondRefresh.completeExceptionally(t);
                }
              });
      refresh2Thread.start();

      release.countDown();

      firstRefresh.get(5, TimeUnit.SECONDS);
      secondRefresh.get(5, TimeUnit.SECONDS);
      toggler.join(5_000);
    } finally {
      release.countDown();
      server.getEventNotifier().unregister(blockingListener);
      subscription1.delete();
      subscription2.delete();
    }
  }

  private static boolean isBlockedCreatingSnapshots(Thread thread) {
    Thread.State state = thread.getState();

    if (state != Thread.State.WAITING
        && state != Thread.State.TIMED_WAITING
        && state != Thread.State.BLOCKED) {
      return false;
    }

    return Stream.of(thread.getStackTrace())
        .anyMatch(frame -> "createRefreshSnapshots".equals(frame.getMethodName()));
  }

  @Test
  void refreshBoundaryPrecedesSnapshotCaptureAndLiveRetraction() throws Exception {
    var subscription = new OpcUaSubscription(client);
    subscription.create();

    try {
      List<Variant[]> events = monitorEvents(subscription, TEST_SEVERITY);

      condition.setAcked(false);
      ByteString replayEventId = condition.currentBranch().getLastEventId();
      pausingCondition.setAcked(false);
      ByteString preRefreshEventId = pausingCondition.currentBranch().getLastEventId();
      EventTestSupport.awaitEvent(
          events, "live retained event to replay", e -> replayEventId.equals(eventIdOf(e)));
      EventTestSupport.awaitEvent(
          events, "live event before refresh", e -> preRefreshEventId.equals(eventIdOf(e)));
      events.clear();

      pausingCondition.enableSnapshotPause();

      UInteger subscriptionId = subscription.getSubscriptionId().orElseThrow();
      Session serverSession = server.getSubscriptions().get(subscriptionId).getSession();
      var refreshResult = new CompletableFuture<Void>();
      var refreshThread =
          new Thread(
              () -> {
                try {
                  server.getConditionManager().conditionRefresh(serverSession, subscriptionId);
                  refreshResult.complete(null);
                } catch (Throwable t) {
                  refreshResult.completeExceptionally(t);
                }
              });
      refreshThread.start();

      assertTrue(
          pausingCondition.awaitSnapshotCaptured(5, TimeUnit.SECONDS),
          "refresh did not reach snapshot capture");

      // Snapshot capture has been reached but not performed for the pausing Condition. This live
      // transition has a distinct EventId and must be queued after RefreshStart but before
      // RefreshEnd. With the old snapshots-before-start ordering it deterministically lands before
      // RefreshStart; after release the now-Retain=false Condition produces no replay snapshot.
      pausingCondition.setAcked(true);
      ByteString liveRetractionEventId = pausingCondition.currentBranch().getLastEventId();
      pausingCondition.releaseSnapshot();

      refreshResult.get(5, TimeUnit.SECONDS);
      refreshThread.join(5_000);

      EventTestSupport.awaitEvent(
          events, "RefreshStart marker", e -> NodeIds.RefreshStartEventType.equals(eventTypeOf(e)));
      EventTestSupport.awaitEvent(
          events, "RefreshEnd marker", e -> NodeIds.RefreshEndEventType.equals(eventTypeOf(e)));

      Variant[] replay =
          EventTestSupport.awaitEvent(
              events,
              "separate retained-condition replay",
              e -> replayEventId.equals(eventIdOf(e)));
      Variant[] liveRetraction =
          EventTestSupport.awaitEvent(
              events,
              "live Retain=false transition",
              e -> liveRetractionEventId.equals(eventIdOf(e)));

      assertEquals(1, countEventId(events, replayEventId), "snapshot identity must replay once");
      assertEquals(
          1,
          countEventId(events, liveRetractionEventId),
          "the distinct live identity must be delivered exactly once");
      assertEquals(
          0,
          countEventId(events, preRefreshEventId),
          "the retracted pausing Condition must not replay its pre-refresh state");
      assertTrue(retainOf(replay), "the separate retained Condition must replay Retain=true");
      assertTrue(!retainOf(liveRetraction), "live transition must retract Retain");

      int startIndex = indexOfEventType(events, NodeIds.RefreshStartEventType);
      int endIndex = indexOfEventType(events, NodeIds.RefreshEndEventType);
      int liveIndex = indexOfEventId(events, liveRetractionEventId);
      int replayIndex = indexOfEventId(events, replayEventId);
      assertTrue(
          startIndex >= 0 && liveIndex > startIndex && endIndex > liveIndex,
          "the distinct live Retain=false event must occur inside the marker bracket");
      assertTrue(
          replayIndex > startIndex && endIndex > replayIndex,
          "the separately identified replay must occur inside the marker bracket");
    } finally {
      pausingCondition.releaseSnapshot();
      subscription.delete();
    }
  }

  @Test
  void conditionEventQueueOverflowYieldsRefreshRequired() throws Exception {
    var subscription = new OpcUaSubscription(client);
    subscription.create();

    try {
      var events = new CopyOnWriteArrayList<Variant[]>();

      OpcUaMonitoredItem item =
          OpcUaMonitoredItem.newEventItem(NodeIds.Server, eventFilter(TEST_SEVERITY));
      item.setQueueSize(uint(1));
      item.setEventValueListener((monitoredItem, eventFields) -> events.add(eventFields));

      subscription.addMonitoredItem(item);
      subscription.synchronizeMonitoredItems();
      assertTrue(item.getCreateResult().orElseThrow().isGood());

      // Burst condition events into the size-1 queue faster than publishing drains it.
      for (int i = 0; i < 5; i++) {
        condition.setAcked(false);
        condition.setAcked(true);
      }

      EventTestSupport.awaitEvent(
          events,
          "RefreshRequired marker after overflow recovery",
          e -> NodeIds.RefreshRequiredEventType.equals(eventTypeOf(e)));
    } finally {
      subscription.delete();
    }
  }

  @Test
  void cleanupFailureDoesNotLeakRefreshGuardOrSuppressRefreshEnd() throws Exception {
    var subscription = new OpcUaSubscription(client);
    subscription.create();

    BaseEventTypeNode eventNode = mock(BaseEventTypeNode.class);
    when(eventNode.getNodeId()).thenReturn(cleanupFailingCondition.getConditionId());
    when(eventNode.getSourceNode()).thenReturn(NodeIds.Server);
    doThrow(new RuntimeException("test snapshot cleanup failure")).when(eventNode).delete();

    cleanupFailingCondition.setSnapshot(new ConditionEventSnapshot(eventNode));
    server.getConditionManager().register(cleanupFailingCondition);

    try {
      List<Variant[]> events = monitorEvents(subscription, TEST_SEVERITY);

      for (int attempt = 0; attempt < 2; attempt++) {
        events.clear();

        assertGood(conditionRefresh(subscription));

        EventTestSupport.awaitEvent(
            events,
            "RefreshEnd after cleanup failure attempt " + attempt,
            e -> NodeIds.RefreshEndEventType.equals(eventTypeOf(e)));
      }

      verify(eventNode, times(2)).delete();
    } finally {
      server.getConditionManager().unregister(cleanupFailingCondition);
      cleanupFailingCondition.setSnapshot(null);
      subscription.delete();
    }
  }

  private CallMethodResult conditionRefresh(OpcUaSubscription subscription) throws Exception {
    return call(
        NodeIds.ConditionType,
        NodeIds.ConditionType_ConditionRefresh,
        new Variant(subscription.getSubscriptionId().orElseThrow()));
  }

  private CallMethodResult call(NodeId objectId, NodeId methodId, Variant... inputs)
      throws Exception {

    CallResponse response = client.call(List.of(new CallMethodRequest(objectId, methodId, inputs)));

    return requireNonNull(response.getResults())[0];
  }

  private static void assertGood(CallMethodResult result) {
    assertTrue(
        result.getStatusCode().isGood(),
        () -> "expected Good status but got " + result.getStatusCode());
  }

  /**
   * Monitor events on the Server Object, selecting [EventId, EventType, Message, Severity, Time,
   * Retain, ConditionId] and matching only events with Severity == {@code severity}.
   */
  private List<Variant[]> monitorEvents(OpcUaSubscription subscription, int severity)
      throws Exception {

    return EventTestSupport.monitorEvents(subscription, NodeIds.Server, eventFilter(severity));
  }

  private static EventFilter eventFilter(int severity) {
    return EventTestSupport.severityEventFilter(
        severity,
        EventTestSupport.eventField(NodeIds.BaseEventType, "EventId"),
        EventTestSupport.eventField(NodeIds.BaseEventType, "EventType"),
        EventTestSupport.eventField(NodeIds.BaseEventType, "Message"),
        EventTestSupport.eventField(NodeIds.BaseEventType, "Severity"),
        EventTestSupport.eventField(NodeIds.BaseEventType, "Time"),
        EventTestSupport.eventField(NodeIds.ConditionType, "Retain"),
        // ConditionId: the NodeId attribute of the condition instance itself (Part 9 §5.5.2).
        new SimpleAttributeOperand(
            NodeIds.ConditionType, new QualifiedName[0], AttributeId.NodeId.uid(), null));
  }

  private static @Nullable ByteString eventIdOf(Variant[] eventFields) {
    return eventFields[0].value() instanceof ByteString eventId ? eventId : null;
  }

  private static @Nullable NodeId eventTypeOf(Variant[] eventFields) {
    return eventFields[1].value() instanceof NodeId eventType ? eventType : null;
  }

  private static @Nullable String messageOf(Variant[] eventFields) {
    return eventFields[2].value() instanceof LocalizedText text ? text.text() : null;
  }

  private static boolean retainOf(Variant[] eventFields) {
    return Boolean.TRUE.equals(eventFields[5].value());
  }

  private static @Nullable NodeId conditionIdOf(Variant[] eventFields) {
    return eventFields[6].value() instanceof NodeId nodeId ? nodeId : null;
  }

  private static long countEventId(List<Variant[]> events, ByteString eventId) {
    return events.stream().filter(e -> eventId.equals(eventIdOf(e))).count();
  }

  private static int indexOfEventType(List<Variant[]> events, NodeId eventTypeId) {
    for (int i = 0; i < events.size(); i++) {
      if (eventTypeId.equals(eventTypeOf(events.get(i)))) {
        return i;
      }
    }
    return -1;
  }

  private static int indexOfEventId(List<Variant[]> events, ByteString eventId) {
    for (int i = 0; i < events.size(); i++) {
      if (eventId.equals(eventIdOf(events.get(i)))) {
        return i;
      }
    }
    return -1;
  }

  private static final class PausingAcknowledgeableCondition extends AcknowledgeableCondition {

    private volatile @Nullable CountDownLatch snapshotCaptured;
    private volatile @Nullable CountDownLatch releaseSnapshot;

    private PausingAcknowledgeableCondition(AcknowledgeableConditionTypeNode node) {
      super(node);
    }

    void enableSnapshotPause() {
      releaseSnapshot = new CountDownLatch(1);
      snapshotCaptured = new CountDownLatch(1);
    }

    void disableSnapshotPause() {
      releaseSnapshot();
      snapshotCaptured = null;
      releaseSnapshot = null;
    }

    boolean awaitSnapshotCaptured(long timeout, TimeUnit unit) throws InterruptedException {
      CountDownLatch captured = snapshotCaptured;
      return captured != null && captured.await(timeout, unit);
    }

    void releaseSnapshot() {
      CountDownLatch release = releaseSnapshot;
      if (release != null) {
        release.countDown();
      }
    }

    @Override
    List<ConditionEventSnapshot> createRefreshSnapshots() throws UaException {
      CountDownLatch captured = snapshotCaptured;
      CountDownLatch release = releaseSnapshot;

      if (captured != null && release != null) {
        captured.countDown();
        try {
          if (!release.await(10, TimeUnit.SECONDS)) {
            throw new UaException(StatusCodes.Bad_Timeout, "timed out awaiting snapshot release");
          }
        } catch (InterruptedException e) {
          Thread.currentThread().interrupt();
          throw new UaException(StatusCodes.Bad_InternalError, e);
        }
      }

      return super.createRefreshSnapshots();
    }
  }

  private static final class CleanupFailingCondition extends AcknowledgeableCondition {

    private volatile @Nullable ConditionEventSnapshot snapshot;

    private CleanupFailingCondition(AcknowledgeableConditionTypeNode node) {
      super(node);
    }

    void setSnapshot(@Nullable ConditionEventSnapshot snapshot) {
      this.snapshot = snapshot;
    }

    @Override
    List<ConditionEventSnapshot> createRefreshSnapshots() {
      ConditionEventSnapshot snapshot = this.snapshot;
      return snapshot != null ? List.of(snapshot) : List.of();
    }
  }
}
