/*
 * Copyright (c) 2026 the Eclipse Milo Authors
 *
 * This program and the accompanying materials are made
 * available under the terms of the Eclipse Public License 2.0
 * which is available at https://www.eclipse.org/legal/epl-2.0/
 *
 * SPDX-License-Identifier: EPL-2.0
 */

package org.eclipse.milo.opcua.sdk.server.conditions;

import static java.util.Objects.requireNonNull;
import static org.eclipse.milo.opcua.stack.core.types.builtin.unsigned.Unsigned.ubyte;
import static org.eclipse.milo.opcua.stack.core.types.builtin.unsigned.Unsigned.uint;
import static org.eclipse.milo.opcua.stack.core.types.builtin.unsigned.Unsigned.ushort;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.time.Duration;
import java.util.List;
import org.eclipse.milo.opcua.sdk.client.OpcUaClient;
import org.eclipse.milo.opcua.sdk.client.subscriptions.OpcUaSubscription;
import org.eclipse.milo.opcua.sdk.core.Reference;
import org.eclipse.milo.opcua.sdk.server.UaNodeManager;
import org.eclipse.milo.opcua.sdk.server.nodes.UaNodeContext;
import org.eclipse.milo.opcua.sdk.server.nodes.UaObjectNode;
import org.eclipse.milo.opcua.sdk.test.AbstractClientServerTest;
import org.eclipse.milo.opcua.sdk.test.EventTestSupport;
import org.eclipse.milo.opcua.sdk.test.TestClient;
import org.eclipse.milo.opcua.sdk.test.TestNamespace;
import org.eclipse.milo.opcua.stack.core.AttributeId;
import org.eclipse.milo.opcua.stack.core.NodeIds;
import org.eclipse.milo.opcua.stack.core.UaException;
import org.eclipse.milo.opcua.stack.core.types.builtin.ByteString;
import org.eclipse.milo.opcua.stack.core.types.builtin.DateTime;
import org.eclipse.milo.opcua.stack.core.types.builtin.LocalizedText;
import org.eclipse.milo.opcua.stack.core.types.builtin.NodeId;
import org.eclipse.milo.opcua.stack.core.types.builtin.QualifiedName;
import org.eclipse.milo.opcua.stack.core.types.builtin.Variant;
import org.eclipse.milo.opcua.stack.core.types.structured.CallMethodRequest;
import org.eclipse.milo.opcua.stack.core.types.structured.CallMethodResult;
import org.eclipse.milo.opcua.stack.core.types.structured.CallResponse;
import org.eclipse.milo.opcua.stack.core.types.structured.EventFilter;
import org.eclipse.milo.opcua.stack.core.types.structured.SimpleAttributeOperand;
import org.jspecify.annotations.Nullable;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

/**
 * Cross-cutting end-to-end scenarios composing the condition runtime's client-visible contract: the
 * shelve → live flow → refresh → acknowledge-replayed-EventId → unshelve lifecycle, operator-action
 * visibility across two clients with refresh isolation, notifier-hierarchy area scoping of a
 * ManagedNamespace condition, and ConditionId select-clause resolution on live and replayed events.
 */
public class ConditionEndToEndTest extends AbstractClientServerTest {

  /** Severity of all events generated by the lifecycle alarm; where clauses match on it. */
  private static final int E2E_SEVERITY = 701;

  /** Severity of all events generated by the area-scoped alarm. */
  private static final int AREA_SEVERITY = 702;

  private ExclusiveLevelAlarm alarm;
  private AlarmCondition areaAlarm;
  private NodeId conditionId;
  private NodeId areaCId;
  private NodeId areaDId;

  @Override
  protected void configureTestNamespace(TestNamespace namespace) {
    namespace.configure(
        (context, nodeManager) -> {
          // The lifecycle alarm's source, wired into the notifier hierarchy from the Server
          // Object by the builder.
          UaObjectNode boiler = addObjectNode(context, nodeManager, "Boiler");

          // An area hierarchy: two sibling areas, each an event notifier, with a source under
          // Area C only (Part 9 clause 6 shape).
          UaObjectNode areaC = addObjectNode(context, nodeManager, "AreaC");
          UaObjectNode areaD = addObjectNode(context, nodeManager, "AreaD");
          UaObjectNode sourceC = addObjectNode(context, nodeManager, "AreaC/Source");

          nodeManager.addReferences(
              new Reference(
                  areaC.getNodeId(), NodeIds.HasEventSource, sourceC.getNodeId().expanded(), true),
              server.getNamespaceTable());

          namespace.registerEventNotifier(areaC);
          namespace.registerEventNotifier(areaD);
          areaCId = areaC.getNodeId();
          areaDId = areaD.getNodeId();

          try {
            alarm =
                ExclusiveLevelAlarm.create(
                    context,
                    b ->
                        b.nodeId(newNodeId("ConditionEndToEndTest/TemperatureAlarm"))
                            .browseName(newQualifiedName("TemperatureAlarm"))
                            .conditionSource(boiler)
                            .inputNode(newNodeId("ConditionEndToEndTest/TemperatureInput"))
                            .severity(ushort(E2E_SEVERITY))
                            .highLimit(90.0)
                            .withShelving(Duration.ofHours(1)));

            areaAlarm =
                AlarmCondition.create(
                    context,
                    b ->
                        b.nodeId(newNodeId("ConditionEndToEndTest/AreaAlarm"))
                            .browseName(newQualifiedName("AreaAlarm"))
                            .conditionSource(sourceC)
                            .severity(ushort(AREA_SEVERITY)));
          } catch (UaException e) {
            throw new RuntimeException(e);
          }

          server.getConditionManager().register(alarm);
          server.getConditionManager().register(areaAlarm);
          conditionId = alarm.getConditionId();
        });
  }

  private UaObjectNode addObjectNode(
      UaNodeContext context, UaNodeManager nodeManager, String name) {

    var node =
        new UaObjectNode(
            context,
            newNodeId("ConditionEndToEndTest/" + name),
            newQualifiedName("ConditionEndToEndTest/" + name),
            LocalizedText.english("ConditionEndToEndTest/" + name),
            LocalizedText.NULL_VALUE,
            uint(0),
            uint(0),
            ubyte(0));

    node.addReference(
        new Reference(
            node.getNodeId(), NodeIds.HasTypeDefinition, NodeIds.BaseObjectType.expanded(), true));
    node.addReference(
        new Reference(
            node.getNodeId(),
            NodeIds.HasComponent,
            NodeIds.ObjectsFolder.expanded(),
            Reference.Direction.INVERSE));

    nodeManager.addNode(node);

    return node;
  }

  @BeforeEach
  void resetConditionState() throws Exception {
    alarm.setInterceptor(new ConditionMethodInterceptor() {});

    // Unshelve if a previous test left the alarm shelved; Bad_ConditionNotShelved is fine.
    call(client, conditionId, NodeIds.ShelvedStateMachineType_Unshelve);

    alarm.evaluate(0.0);
    alarm.setAcked(true);
    areaAlarm.setActive(false);
    areaAlarm.setAcked(true);
  }

  /**
   * The full operator lifecycle: shelve an active alarm, live events keep flowing while shelved,
   * refresh replays the retained trunk with its original identity, Acknowledge accepts the replayed
   * EventId, then unshelve and return-to-normal complete the lifecycle with the Retain retraction.
   */
  @Test
  void shelveRefreshAcknowledgeUnshelveLifecycle() throws Exception {
    var subscription = new OpcUaSubscription(client);
    subscription.create();

    try {
      List<Variant[]> events = monitorEvents(subscription, E2E_SEVERITY);

      // Activate through the limit machinery: the sampled value violates the High limit.
      alarm.evaluate(95.0);
      EventTestSupport.awaitEvent(
          events,
          "activation event",
          e -> "Active/High".equals(messageOf(e)) && retainOf(e) && !ackedIdOf(e));
      assertTrue(alarm.isActive());

      // Shelve via ConditionId dispatch with the type-declaration MethodId.
      assertGood(
          call(
              client,
              conditionId,
              NodeIds.ShelvedStateMachineType_TimedShelve,
              new Variant(600_000.0)));
      EventTestSupport.awaitEvent(
          events,
          "TimedShelved event",
          e -> "TimedShelved".equals(messageOf(e)) && suppressedOrShelvedOf(e));

      // Shelved alarms keep emitting; the server does not withhold delivery — an operator
      // AddComment arrives live with SuppressedOrShelved=true in the fields.
      assertGood(
          call(
              client,
              conditionId,
              NodeIds.ConditionType_AddComment,
              new Variant(alarm.currentBranch().getLastEventId()),
              new Variant(LocalizedText.english("shelved for the shift"))));
      EventTestSupport.awaitEvent(
          events,
          "live comment while shelved",
          e -> "Comment added".equals(messageOf(e)) && suppressedOrShelvedOf(e));

      // Refresh replays the retained trunk carrying its original EventId and Time.
      ByteString lastEventId = alarm.currentBranch().getLastEventId();
      DateTime lastEventTime = alarm.currentBranch().getLastEventTime();
      events.clear();

      assertGood(conditionRefresh(client, subscription));

      EventTestSupport.awaitEvent(
          events, "RefreshStart marker", e -> NodeIds.RefreshStartEventType.equals(eventTypeOf(e)));
      Variant[] replay =
          EventTestSupport.awaitEvent(
              events, "retained trunk replay", e -> lastEventId.equals(eventIdOf(e)));
      EventTestSupport.awaitEvent(
          events, "RefreshEnd marker", e -> NodeIds.RefreshEndEventType.equals(eventTypeOf(e)));

      assertEquals(lastEventTime, replay[4].value(), "replay must carry the original Time");
      assertTrue(retainOf(replay));
      assertTrue(suppressedOrShelvedOf(replay), "replay must reflect the shelved state");
      assertEquals(conditionId, conditionIdOf(replay));

      // Acknowledge accepts the replayed EventId.
      assertGood(
          call(
              client,
              conditionId,
              NodeIds.AcknowledgeableConditionType_Acknowledge,
              new Variant(eventIdOf(replay)),
              new Variant(LocalizedText.english("ack via replayed EventId"))));
      EventTestSupport.awaitEvent(
          events,
          "acknowledged while shelved",
          e -> "Acknowledged".equals(messageOf(e)) && ackedIdOf(e) && suppressedOrShelvedOf(e));
      assertTrue(alarm.isAcked());

      // Unshelve, then return to normal: acknowledged and inactive, so the lifecycle completes
      // with the single Retain retraction.
      assertGood(call(client, conditionId, NodeIds.ShelvedStateMachineType_Unshelve));
      EventTestSupport.awaitEvent(
          events,
          "Unshelved event",
          e -> "Unshelved".equals(messageOf(e)) && !suppressedOrShelvedOf(e));

      alarm.evaluate(50.0);
      EventTestSupport.awaitEvent(
          events,
          "return-to-normal retraction",
          e -> "Inactive".equals(messageOf(e)) && !retainOf(e));
      assertFalse(alarm.isActive());
      assertFalse(alarm.isRetained());
    } finally {
      subscription.delete();
    }
  }

  /**
   * Two clients, two subscriptions: operator actions performed from one session are visible as
   * events on the other, and a refresh of one session's subscription produces no traffic on the
   * other's.
   */
  @Test
  void operatorActionsVisibleAcrossClientsAndRefreshIsolationHolds() throws Exception {
    OpcUaClient client2 = TestClient.create(server, configBuilder -> {});
    client2.connect();

    var subscription1 = new OpcUaSubscription(client);
    subscription1.create();
    var subscription2 = new OpcUaSubscription(client2);
    subscription2.create();

    try {
      List<Variant[]> events1 = monitorEvents(subscription1, E2E_SEVERITY);
      List<Variant[]> events2 = monitorEvents(subscription2, E2E_SEVERITY);

      alarm.evaluate(95.0);
      EventTestSupport.awaitEvent(
          events1, "activation on client 1", e -> "Active/High".equals(messageOf(e)));
      EventTestSupport.awaitEvent(
          events2, "activation on client 2", e -> "Active/High".equals(messageOf(e)));

      // Acknowledge from client 2; the resulting event is visible to client 1.
      assertGood(
          call(
              client2,
              conditionId,
              NodeIds.AcknowledgeableConditionType_Acknowledge,
              new Variant(alarm.currentBranch().getLastEventId()),
              new Variant(LocalizedText.english("acked from the other client"))));

      EventTestSupport.awaitEvent(
          events1,
          "acknowledge from client 2 visible on client 1",
          e -> "Acknowledged".equals(messageOf(e)) && ackedIdOf(e));
      EventTestSupport.awaitEvent(
          events2,
          "acknowledge visible on client 2",
          e -> "Acknowledged".equals(messageOf(e)) && ackedIdOf(e));

      // Refresh isolation: refreshing client 1's subscription produces a bracket there and no
      // traffic on client 2's subscription.
      events1.clear();
      events2.clear();

      assertGood(conditionRefresh(client, subscription1));

      EventTestSupport.awaitEvent(
          events1,
          "RefreshEnd on the refreshed subscription",
          e -> NodeIds.RefreshEndEventType.equals(eventTypeOf(e)));
      EventTestSupport.assertNoEvent(
          events2, "refresh traffic on the other session's subscription", e -> true);
    } finally {
      subscription1.delete();
      subscription2.delete();
      client2.disconnect();
    }
  }

  /**
   * A condition in a ManagedNamespace behind an area hierarchy: an item on its own area sees the
   * alarm, an item on the sibling area does not, and an item on the Server Object sees everything.
   */
  @Test
  void areaScopedItemSeesAlarmSiblingAreaDoesNotServerSeesAll() throws Exception {
    var subscription = new OpcUaSubscription(client);
    subscription.create();

    try {
      List<Variant[]> areaCEvents =
          EventTestSupport.monitorEvents(subscription, areaCId, eventFilter(AREA_SEVERITY));
      List<Variant[]> areaDEvents =
          EventTestSupport.monitorEvents(subscription, areaDId, eventFilter(AREA_SEVERITY));
      List<Variant[]> serverEvents =
          EventTestSupport.monitorEvents(subscription, NodeIds.Server, eventFilter(AREA_SEVERITY));

      areaAlarm.setActive(true);
      ByteString eventId = areaAlarm.currentBranch().getLastEventId();

      EventTestSupport.awaitEvent(
          areaCEvents, "alarm on its own area's item", e -> eventId.equals(eventIdOf(e)));
      EventTestSupport.awaitEvent(
          serverEvents, "alarm on the Server item", e -> eventId.equals(eventIdOf(e)));
      EventTestSupport.assertNoEvent(
          areaDEvents, "alarm on the sibling area's item", e -> eventId.equals(eventIdOf(e)));
    } finally {
      subscription.delete();
    }
  }

  /**
   * The ConditionId select-clause operand (the NodeId attribute of the condition instance, Part 9
   * §5.5.2) resolves to the condition instance NodeId on live events and on refresh replay.
   */
  @Test
  void conditionIdOperandResolvesOnLiveAndReplayedEvents() throws Exception {
    var subscription = new OpcUaSubscription(client);
    subscription.create();

    try {
      List<Variant[]> events = monitorEvents(subscription, E2E_SEVERITY);

      alarm.evaluate(95.0);
      Variant[] live =
          EventTestSupport.awaitEvent(
              events, "live activation event", e -> "Active/High".equals(messageOf(e)));
      assertEquals(conditionId, conditionIdOf(live), "ConditionId must resolve on live events");

      ByteString lastEventId = alarm.currentBranch().getLastEventId();
      events.clear();

      assertGood(conditionRefresh(client, subscription));

      Variant[] replay =
          EventTestSupport.awaitEvent(
              events, "retained trunk replay", e -> lastEventId.equals(eventIdOf(e)));
      assertEquals(
          conditionId, conditionIdOf(replay), "ConditionId must resolve on replayed events");
    } finally {
      subscription.delete();
    }
  }

  private CallMethodResult conditionRefresh(OpcUaClient client, OpcUaSubscription subscription)
      throws Exception {

    return call(
        client,
        NodeIds.ConditionType,
        NodeIds.ConditionType_ConditionRefresh,
        new Variant(subscription.getSubscriptionId().orElseThrow()));
  }

  private CallMethodResult call(
      OpcUaClient client, NodeId objectId, NodeId methodId, Variant... inputs) throws Exception {

    CallResponse response = client.call(List.of(new CallMethodRequest(objectId, methodId, inputs)));

    return requireNonNull(response.getResults())[0];
  }

  private static void assertGood(CallMethodResult result) {
    assertTrue(
        requireNonNull(result.getStatusCode()).isGood(),
        () -> "expected Good status but got " + result.getStatusCode());
  }

  /**
   * Monitor events on the Server Object, selecting [EventId, EventType, Message, Severity, Time,
   * Retain, ConditionId, SuppressedOrShelved, AckedState/Id] and matching only events with Severity
   * == {@code severity}.
   */
  private List<Variant[]> monitorEvents(OpcUaSubscription subscription, int severity)
      throws Exception {

    return EventTestSupport.monitorEvents(subscription, NodeIds.Server, eventFilter(severity));
  }

  private static EventFilter eventFilter(int severity) {
    return EventTestSupport.severityEventFilter(
        severity,
        EventTestSupport.eventField(NodeIds.BaseEventType, "EventId"),
        EventTestSupport.eventField(NodeIds.BaseEventType, "EventType"),
        EventTestSupport.eventField(NodeIds.BaseEventType, "Message"),
        EventTestSupport.eventField(NodeIds.BaseEventType, "Severity"),
        EventTestSupport.eventField(NodeIds.BaseEventType, "Time"),
        EventTestSupport.eventField(NodeIds.ConditionType, "Retain"),
        // ConditionId: the NodeId attribute of the condition instance itself (Part 9 §5.5.2).
        new SimpleAttributeOperand(
            NodeIds.ConditionType, new QualifiedName[0], AttributeId.NodeId.uid(), null),
        EventTestSupport.eventField(NodeIds.AlarmConditionType, "SuppressedOrShelved"),
        EventTestSupport.eventField(NodeIds.AcknowledgeableConditionType, "AckedState", "Id"));
  }

  private static @Nullable ByteString eventIdOf(Variant[] eventFields) {
    return eventFields[0].value() instanceof ByteString eventId ? eventId : null;
  }

  private static @Nullable NodeId eventTypeOf(Variant[] eventFields) {
    return eventFields[1].value() instanceof NodeId eventType ? eventType : null;
  }

  private static @Nullable String messageOf(Variant[] eventFields) {
    return eventFields[2].value() instanceof LocalizedText text ? text.text() : null;
  }

  private static boolean retainOf(Variant[] eventFields) {
    return Boolean.TRUE.equals(eventFields[5].value());
  }

  private static @Nullable NodeId conditionIdOf(Variant[] eventFields) {
    return eventFields[6].value() instanceof NodeId nodeId ? nodeId : null;
  }

  private static boolean suppressedOrShelvedOf(Variant[] eventFields) {
    return Boolean.TRUE.equals(eventFields[7].value());
  }

  private static boolean ackedIdOf(Variant[] eventFields) {
    return Boolean.TRUE.equals(eventFields[8].value());
  }
}
